<div class="viewpage" id="toplink">
    <h3 class="page-headline"> <?= $this->row->headline ?></h3>

    <div class="page-content">
        <?= $this->row->content ?>
    </div>

    <hr/>
    <div class="">
        <small style="color: #466666"><i>Autor: <b><?= $this->row->author ?></b></i></small>
        <small id="create-date" style="color: #74c2c1"><?= $this->transEsc('Create Date') ?>
            : <?= $this->cDate ?></small>
        <? if (!empty($this->modDate)) : ?>
            <br>
            <small id="modify-date" style="color: #6579c2">Last modified:&nbsp;<?= $this->modDate ?></small>
        <? endif; ?>
    </div>
</div>