<?php
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - Add'));
$this->headLink(['rel' => 'stylesheet', 'href' => $this->basePath() . "/themes/hebisbs3/js/wysiwyg-editor/summernote.css"]);
$this->headScript()->appendFile($this->basePath() . "/themes/hebisbs3/js/wysiwyg-editor/summernote.min.js");
$activeLang = $this->layout()->userLang;
?>
<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">
        <div class="alert alert-warning alert-dismissible" role="alert" id="multilang-warning" style="display: none">
            <p>Language is empty</p>
        </div>
        <h4 style="color: #00A5E3"><i><?= $this->translate('Add New Page') ?></i></h4>
        <ul class="nav nav-tabs">
            <? foreach ($this->langs as $code => $language) : ?>
                <li data-href="<?= $language ?>" id="lang-tabs"><a data-toggle="tab"
                                                                   href="#<?= $language ?>-form"><?= $code ?></a>
                </li>
            <? endforeach; ?>
            <li data-href="other-lang" id="lang-tabs"><a data-toggle="tab"
                                                         href="#other-lang-form"><span
                            class="hds-icon-plus-squared-alt"></span></a>
            </li>
        </ul>
        <form id="new post" method="post">
            <div class="tab-content">
                <? foreach ($this->langs as $code => $language) : ?>
                    <div id="<?= $language ?>-form" class="tab-pane fade">
                        <input type="hidden" class="form-control" name="sp-lang[]" value="<?= $code ?>">
                        <div class="form-group">
                            <input type="text" class="form-control" name="sp-headline[]" placeholder="Headline"
                                   id="sp-headline" style="font-size: large">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control wysiwig-text" name="sp-content[]">
                        </div>
                    </div>
                <? endforeach; ?>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon" id="sp-<?= $this->transEsc('author'); ?>"><span
                                class="hds-icon-user-1"></span></span>
                    <input id="sp-author" type="text" placeholder="<?= $this->transEsc('author'); ?>" name="sp-author"
                           class="form-control">
                </div>
            </div>

            <button class="btn btn-default" id="sp-save"><?= $this->transEsc('Save'); ?></button>
        </form>
    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
