<?php
$this->headTitle($this->translate('VuFind Administration - Add Custom Page'));
?>

<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h4 style="color: #00A5E3"><?= $this->translate('➕ Add New Page') ?></h4>

        <div class="form-group" style="width: 85%">
            <form id="new post">
                <p><textarea id="headline" name="headline" rows="1"
                             style="width: 100%; font-size: large; font-weight: 700">Headline</textarea></p>
                <p><textarea name="content" id="content" rows="11" style="width: 100%">Content</textarea></p>
                <input type="submit" formmethod="post" formaction="" value="Save Post">

            </form>
        </div>

    </div>

    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>


<!--WYSIWYG Script-->
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">
    bkLib.onDomLoaded(function () {
        nicEditors.editors.push(
            new nicEditor().panelInstance(
                document.getElementById('content')));
    });
</script>
