<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - Edit'));
$this->headLink(['rel' => 'stylesheet', 'href' => $this->basePath() . "/themes/hebisbs3/js/wysiwyg-editor/summernote.css"]);
$this->headScript()->appendFile($this->basePath() . "/themes/hebisbs3/js/wysiwyg-editor/summernote.min.js");
?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h3 style="color: #00A5E3"><span class="hds-icon-pencil-1"></span><i><?= $this->translate('Edit Page') ?></i>
        </h3>
        <div class="form-group" style="width: 85%">
            <form id="edit post">
                <p><textarea id="headline" name="headline" rows="1"
                             style="width: 100%; font-size: large; font-weight: 700"><?= $this->row->headline ?></textarea>
                </p>
                <p><textarea id="sp_WYSWIG" name="content"
                             style="width: 100%"><?= $this->row->content ?></textarea></p>
                <input type="submit" formmethod="post" value="Save Changes">
            </form>
        </div>
    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>

