<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - Home'));
$this->headScript()->appendFile("https://code.jquery.com/ui/1.12.1/jquery-ui.js");
?>


<div class="row">
    <h3><span class="hds-icon-journal"></span>&nbsp;Static<b>Pages</b></h3>
    <hr>
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <div class="delete-confirm" style="
        display:none;
        position: absolute;
        z-index: 1000;
        width: 90%;
        height: 100%;">
            <div class="col-xs-12 col-sm-2"></div>
            <div class="col-xs-12 col-sm-8">
                <div class="confff" style="
                border: groove rgba(255,75,0,0.25);
            background-color: rgba(255,255,255,0.75);
            padding: 20px 10px 10px 10px;
            margin: 10px auto;
            text-align: center"
                >
                    <p><b>Sicher?</b></p>
                    <div class="conf-buttons">
                        <button id="del">Jaaa</button>
                        <button style="color: darkred">Ja!</button>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-2"></div>
        </div>

        <!-- xs sm md lg -->

        <div class="row">
            <div class="col-xs-12 col-sm-10">
                <span class="hds-icon-plus-circled"></span>&nbsp;
                <a href="<?= $this->url('adminstaticpages/add') ?>"><i>Neue Seite Hinzufügen</i></a>
            </div>
            <div class="col-xs-12 col-sm-2">

            </div>
        </div>
        <?
        $symbols = array(
            'visible' => '<span class="hds-icon-eye green"></span>',
            'unvisible' => '<span class="hds-icon-eye-off red"></span>',
            'delete' => '<span class="hds-icon-trash"></span>',
            'edit' => '<span class="hds-icon-pencil-1"></span>'
        ); ?>
        <? foreach ($this->rows as $row) : ?>
            <? $visibilitySymbol = ($row->visible == 1) ? $symbols['visible'] : $symbols['unvisible']; ?>
            <div class="row" id="<?= $row->id ?>">
                <div class="col-xs-12 col-sm-10">
                    <span class="eye-page-visibility"
                          href="<?= $this->url('adminstaticpages/json', ['method' => 'visible', 'id' => $row->id]) ?>">
                        <?= ($row->visible == 1) ? $symbols['visible'] : $symbols['unvisible']; ?></span>
                    <a href="<?= $this->url('adminstaticpages/view', ['id' => $row->id]) ?>"><?= $row->headline ?></a>
                </div>
                <div class="col-xs-12 col-sm-2">
                    <a href="<?= $this->url('adminstaticpages/edit', ['id' => $row->id]) ?>"><?= $symbols['edit'] ?></a>&nbsp;
                    <span class="delete-post" style="cursor: hand"
                          href="<?= $this->url('adminstaticpages/json', ['method' => 'delete', 'id' => $row->id]) ?>"><?= $symbols['delete'] ?></span>
                </div>

            </div>
        <? endforeach; ?>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>