<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - Home'));
$this->headScript()->appendFile("https://code.jquery.com/ui/1.12.1/jquery-ui.js");
?>

<!--Modal-->
<div class="modal fade" id="sp-delete-confirmation" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" id="cross">&times;</button>
                <div class="pull-left col-md-2" style="font-size:300%">
                    <span class="hds-icon-trash-empty"><!-- --></span>
                </div>
                <p id="sp-delete-question">Bist du sicher, dass du die folgende Seite löschen willst?<i></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"
                        id="delete-confirmation-button"><?= $this->translate('Delete') ?></button>
            </div>
        </div>
    </div>
</div>
<!--End of Modal-->
<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h3><span class="hds-icon-journal"></span>&nbsp;Static<b>Pages</b></h3>
        <hr>
        <div class="post">
            <div class="col-xs-12 col-sm-10">
                <span class="hds-icon-plus-circled"></span>
                <a href="<?= $this->url('adminstaticpages/add') ?>"><i>Neue Seite Hinzufügen</i></a>
            </div>
            <div class="col-xs-12 col-sm-2">

            </div>
        </div>
        <?
        $visibilitySymbols = array(
            'visible' => '<span class="hds-icon-eye green"></span>',
            'unvisible' => '<span class="hds-icon-eye-off red"></span>',
        ); ?>
        <? foreach ($this->rows as $row) : ?>
            <div class="post" id="<?= $row->id ?>" data-href="<?= $row->headline ?>">
                <div class="col-xs-12 col-sm-10">
                    <span class="sp-page-visibility"
                          href="<?= $this->url('adminstaticpages/json', ['method' => 'visible', 'id' => $row->id]) ?>">
                        <?= ($row->visible == 1) ? $visibilitySymbols['visible'] : $visibilitySymbols['unvisible']; ?></span>
                    <a href="<?= $this->url('adminstaticpages/preview', ['id' => $row->id]) ?>"><?= $row->headline ?></a>
                </div>
                <div class="col-xs-12 col-sm-2">
                    <a href="<?= $this->url('adminstaticpages/edit', ['id' => $row->id]) ?>">
                        <span class="hds-icon-edit"><!--></span></a>
                    <span class="sp-delete-button" id="<?= $row->id ?>"
                          href="<?= $this->url('adminstaticpages/json', ['method' => 'delete', 'id' => $row->id]) ?>">
                        <span class="hds-icon-trash"><!--></span>
                    </span>
                </div>
            </div>
        <? endforeach; ?>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
