<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - View'));
?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">

        <div class="<?= $this->layoutClass('viewpage') ?>" style="width: 85%">

            <h3><b> <?= $this->row->headline ?> </b></h3>
            <small style="color: #466666"><i>Autor: <b><?= $this->row->author ?></b></i></small>
            <hr>
            <article style="width: inherit"><?= $this->row->content ?></article>
            <hr>
            <small id="create-date" style="color: #74c2c1">Create Date:&nbsp;<?= $this->cDate ?></small>
            <br>
            <small id="modify-date" style="color: #6579c2">Last modified:&nbsp;<?= $this->modDate ?></small>
        </div>
    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
