<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - View'));

?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">

        <div class="<?= $this->layoutClass('viewpage') ?>" style="width: 85%">

            <? $var = $this->dateFormat($this->row->createDate);
            echo
                '<h3><b>' . $this->row->headline . '</b></h3>' .
                '<i><small style="color: #466666">Autor: <b>' . $this->row->author . '</b></small></i><br />' .
                '' . '<br />' .
                '<article style="width: inherit">' . $this->row->content . '</article><br/><small style="color: #74c2c1">'
                . $this->row->createDate . $var . '</small>'
            ?>

        </div>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
