<?
// Set page title.
$this->headTitle($this->translate('VuFind Administration - HeBIS Bulletin'));
?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h2>📝 Das <b>Bulletin</b></h2>


        <a href="<?= $this->url('staticpages', array('action' => 'addpage')) ?>"><?= $this->transEsc('➕ Add New Page') ?></a>

        <ul>
            <?
            foreach ($this->rows as $row) {
                echo "<li>" . $row->id . ".&nbsp" . $row->headline . " ¦ " . $row->content . "&nbsp;<a href='home.phtml'>✏</a>❌</a></li>";
            }
            ?>
        </ul>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
