<?
// Set page title.
$this->headTitle($this->translate('VuFind Administration - HeBIS Bulletin'));
?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h2>📝 Das <b>Bulletin</b></h2>
        <hr>
        <table width="80%" cellspacing="20">
            <tr>
                <td>➕</td>
                <td><a href="<?= $this->url('staticpages/add') ?>"><i>Neue Seite Hinzufügen</i></a></td>
            </tr>
            <?
            $symbols = array(
                'visible' => '👁',
                'unvisible' => '🚫',
                'delete' => '🗑️',
                'edit' => '📝'
            );
            foreach ($this->rows as $row) {
                $visibilitySymbol = ($row->visible == 1) ? $symbols['visible'] : $symbols['unvisible'];

                echo '<tr><td>' . $visibilitySymbol . '</td><td><a href="' . $this->url('staticpages/view', ['id' => $row->id]) . '">' . $row->headline .
                    '</a></td><td><a href="' . $this->url('staticpages/edit', ['id' => $row->id]) . '">' . $symbols['edit'] . '</td><td><a href="' . $this->url('staticpages/delete', ['id' => $row->id]) . '">' . $symbols['delete'] . '</td></tr>';
            }
            ?>
        </table>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
