<?
$this->headTitle($this->translate('Static Pages'));
?>

<!-- TODO: Grids -->
<div class="page-header"><h2>Static Pages</h2></div>
<div class="row"> <!--style="padding: 50px"-->
    <? foreach ($this->rows as $row) : ?>
        <? if ($row->visible == 1) : ?>
            <div class="col-xs-10 col-lg-4">
                <a href="<?= $this->url('staticpages/view', ['id' => $row->id]) ?>" class="thumbnail" id="sp">
                    <span class="hds-icon-journal" style="font-size: 300%"></span>
                    <div class="caption">
                        <h3><strong><?= $row->headline ?></strong></h3>
                        <p><?= $row->caption ?></p>
                    </div>
                </a>
            </div>
        <? endif; ?>
    <? endforeach; ?>

</div>
