<?
// Set page title.
$this->headTitle($this->translate('VuFind Administration - Static Page View'));

?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">

        <div class="<?= $this->layoutClass('viewpage') ?>">

            <? echo
                '<h3><b>' . $this->row->headline . '</b><br />' .
                '<small style="color: #81a8ce"><i>last modified: ' . $this->row->changeDate . '</i></small></h3>' .
                '' . '<br />' .
                '<article style="width: 70%">' . $this->row->content . '</article>'
            ?>

        </div>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
