<? if (!empty($this->ezbLinks)) : ?>
    <? foreach ($this->ezbLinks as $ezbLink) : ?>
        <p><?= $ezbLink['ampel'] ?> <?= $ezbLink['direktlink'] ?>
        <? if (!empty($this->infoLink)) : ?>
            <a href="<?= $this->infoLink ?>" target="_blank"><span class="hds-icon-info-circled info"><!-- --></span></a></span>
        <? endif; ?>
        </p>
    <? endforeach; ?>
<? else : ?>
    <? if (!empty($this->rediLink)) : ?>
        <a title="<?= $this->translate("CL-" . $this->rediLink['Text']) ?>" href="<?= $this->rediLink['Url'] ?>" target="_blank"><?= $this->translate("CL-" . $this->rediLink['Text']) ?></a></span>
    <? endif; ?>
<? endif; ?>
