<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");
// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

if ($driver instanceof \Hebis\RecordDriver\SolrMarc) {
    $searchClassId = "Solr";
} else {
    $searchClassId = "EDS";
}

// Set up breadcrumbs:
$lastSearchTerm = $this->searchMemory()->getLastSearchTerm($searchClassId);
$shortTitle = strpos($searchClassId, "EDS") !== false ? $this->edsShortTitle($this->driver) : $this->singleRecordTitleStatementHeadline($this->driver);

$this->layout()->breadcrumbs = !empty($lastSearchTerm) ? "<li>" . $this->searchMemory()->getLastSearchLinkOfSearchClassId($this->transEsc('Search').': '.$lastSearchTerm, $searchClassId, '', '</li> ') : '';
$this->layout()->breadcrumbs .= !empty($shortTitle) ? '<li class="active">'.$this->truncate($shortTitle, 30).'</li>' : "";


//$this->layout()->title = $this->singleRecordTitleStatementHeadline($this->driver);
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
    <ul class="pager hidden-print hidden-md hidden-lg">
        <? if ($this->scrollData['previousRecord']): ?>
            <li>
                <a href="<?= $this->recordLink()->getUrl($this->scrollData['previousRecord']) ?>"
                   title="<?= $this->transEsc('Previous Search Result') ?>"><span class="hds-icon-left-open"><!-- --> </span><span class="sr-only"><?= $this->transEsc('Prev') ?></span></a>
            </li>
        <? else: ?>
            <li class="disabled"><span class="hds-icon-left-open"><!-- --> </span><span class="sr-only"><?= $this->transEsc('Prev') ?></span></li>
        <? endif; ?>
        <li><span><?= $this->localizedNumber($this->scrollData['currentPosition']) . ' / ' . $this->localizedNumber($this->scrollData['resultTotal']) //' ' . $this->transEsc('results') ?></span></li>
        <? if ($this->scrollData['nextRecord']): ?>
            <li>
                <a href="<?= $this->recordLink()->getUrl($this->scrollData['nextRecord']) ?>"
                   title="<?= $this->transEsc('Next Search Result') ?>"><span class="sr-only"><?= $this->transEsc('Next') ?></span><span class="hds-icon-right-open"> <!-- --></span></a>
            </li>
        <? else: ?>
            <li class="disabled"><span class="sr-only"><?= $this->transEsc('Next') ?></span><span class="hds-icon-right-open"> <!-- --></span></li>
        <? endif; ?>
    </ul>
<? endif; ?>

    <div class="view-record">
        <div class="record recordId source<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" id="record">
            <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId"
                   id="record_id"/>
            <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>"
                   class="hiddenSource"/>
            <?= $this->flashmessages() ?>
            <?= $this->record($this->driver)->getCoreMetadata() ?>
        </div>


    </div>
