<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");
// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

if ($driver instanceof \Hebis\RecordDriver\SolrMarc) {
    $searchClassId = "Solr";
} else {
    $searchClassId = "EDS";
}

// Set up breadcrumbs:
$lastSearchTerm = $this->searchMemory()->getLastSearchTerm($searchClassId);
$shortTitle = strpos($searchClassId, "EDS") !== false ? $this->edsShortTitle($this->driver) : $this->singleRecordTitleStatementHeadline($this->driver);

$this->layout()->breadcrumbs = !empty($lastSearchTerm) ? "<li>" . $this->searchMemory()->getLastSearchLinkOfSearchClassId($this->transEsc('Search').': '.$lastSearchTerm, $searchClassId, '', '</li> ') : '';
$this->layout()->breadcrumbs .= !empty($shortTitle) ? '<li class="active">'.$this->truncate($shortTitle, 30).'</li>' : "";


//$this->layout()->title = $this->singleRecordTitleStatementHeadline($this->driver);
?>


<div class="row">

    <div class="col-md-9 <? //$this->layoutClass('mainbody') ?>">

        <div class="view-record">
            <div class="record recordId source<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" id="record">
                <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId"
                       id="record_id"/>
                <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>"
                       class="hiddenSource"/>
                <?= $this->flashmessages() ?>
                <?= $this->record($this->driver)->getCoreMetadata() ?>
            </div>
        </div>

        <? if (count($this->tabs) > 0): ?>
            <a name="tabnav"></a>
            <div class="record-tabs tab-description">
                <ul class="nav nav-tabs">
                    <? foreach ($this->tabs as $tab => $obj): ?>
                        <? // add current tab to breadcrumbs if applicable:
                        $disabled = false;
                        $desc = $obj->getDescription();
                        $tab_classes = array();
                        if (0 === strcasecmp($this->activeTab, $tab)) {
                            if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                                $tab_classes[] = 'active';
                            }
                            $tab_classes[] = 'initiallyActive';
                            $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                            $activeTabObj = $obj;
                        }
                        if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
                        if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
                        if (!$obj->hasContents()) { $tab_classes[] = 'disabled';  $disabled = true;}
                        ?>
                        <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
                            <? if (!$disabled) : ?>
                                <a class="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"<? if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs) && !$disabled):?> data-background<? endif ?>><?=$this->transEsc($desc)?></a>
                            <? else : ?>
                                <a href="javascript:return false;"><?=$this->transEsc($desc)?></a>
                            <? endif; ?>
                        </li>
                    <? endforeach; ?>
                </ul>

                <div class="tab-content">
                    <? $loadInitialTabWithAjax = $this->loadInitialTabWithAjax; ?>
                    <? if (!$loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
                        <div class="tab-pane active <?=$this->activeTab ?>-tab">
                            <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
                        </div>
                    <? endif; ?>
                </div>
            </div>
        <? endif; ?>
    </div>
    <div class="col-md-3 <? $this->layoutClass('sidebar') ?>">

        <div class="text-center">


            <? /* Display qrcode if appropriate: */ ?>
            <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
            <? if ($QRCode): ?>
                <span class="hidden-xs">
                      <br/><img alt="<?= $this->translate('QR Code') ?>" class="qrcode"
                                src="<?= $this->escapeHtmlAttr($QRCode); ?>"/>
                    </span>
            <? endif; ?>
        </div>

        <? // if you have a preview tab but want to move or remove the preview link
        // from this area of the record view, this can be split into
        // getPreviewData() (should stay here) and
        // getPreviewLink() (can go in your desired tab) ?>
        <? // $this->record($this->driver)->getPreviews() ?>
        <hr/>
        <?= $this->record($this->driver)->getToolbar() ?>
        <hr/>

        <? $isbns = $this->singleRecordInternationalStandardBookNumber($this->driver, true); ?>
        <? if (!empty($isbns)) : ?>
            <div id="other-editions" data-xid="<?=$isbns['0']?>">

            </div>
        <? endif;?>
        <?= $this->render('RecordDriver/SolrDefault/result-bibtip.phtml'); ?>
        <!--
            <? /*foreach ($this->related()->getList($this->driver) as $current): ?>
                <?= $this->related()->render($current) ?>
            <? endforeach; */?>
            -->
    </div>
</div>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>