<?
// Set page title.
$this->headTitle($this->translate('Advanced Search'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>';
$lastSearchLink = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'));
$this->layout()->breadcrumbs .= !empty($lastSearchLink)
    ? $lastSearchLink : $this->transEsc('Search');
$this->layout()->breadcrumbs .= '</li> <li class="active">' . $this->transEsc('Advanced') . '</li>';

// Set up saved search details:
if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();
    $hiddenFilters = $this->saved->getParams()->getHiddenFilters();
} else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
    $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, true);
}

// Step 1: Load the javascript
$this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
);
// Step 2: Build the page
$this->headScript()->appendScript(
    $this->partial(
        isset($this->buildPageOverride) ? $this->buildPageOverride : 'search/advanced/build_page.phtml',
        ['options' => $this->options, 'searchDetails' => $searchDetails]
    )
);

// Collect previous search queries
$setSearchGroups = [];
$setGroupCount = 0;
$setQueries = [];
if (isset($searchDetails) && is_object($searchDetails)) {
    foreach ($searchDetails->getQueries() as $group => $searchGroup) {
        $setSearchGroups[$group] = $searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator();
        if ($setGroupCount < $group) {
            $setGroupCount = $group;
        }
        if (!isset($setQueries[$group])) {
            $setQueries[$group] = [];
        }
        foreach ($searchGroup->getQueries() as $search) {
            $setQueries[$group][] = $search;
        }
    }
}
$popOverJs = <<<POPOVER
    $(document).ready(function(){
        options = {
                html : true,
                trigger : "focus",
                container : 'body',
                placement : 'auto',
                content : function() {
                    return $(this).data('content')
                },
                delay : 0
            };    
        
        $('.help-searchterm, .help-type, .help-bool, .help-join').popover(options);
        document.addEventListener("DOMNodeInserted", function(event){
            var element = event.target;
            $(element).find('.help-searchterm, .help-type, .help-bool, .help-join').popover(options);
        });
        $('select[multiple="multiple"]').multiselect({
            enableFiltering: true
        })
        .on('reset', function() {
            $('select[multiple="multiple"]').each(function() {
                $(this).prop('selected', false);
            });
            $('select[multiple="multiple"]').multiselect('refresh');
        });
    });
    
    
POPOVER;

$this->headScript()->appendScript($popOverJs);
$this->headScript()->appendFile("bootstrap-multiselect.js");
?>

    <?= $this->flashmessages() ?>
    <div role="search">
        <form name="searchForm" id="advSearchForm" method="get"
              action="<?= $this->url($this->options->getSearchAction()) ?>" class="form-horizontal">
            <? foreach ($hiddenFilters as $key => $filter): ?>
                <? foreach ($filter as $value): ?>
                    <input type="hidden" name="hiddenFilters[]"
                           value="<?= $this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value) ?>"/>
                <? endforeach; ?>
            <? endforeach; ?>
            <div class="row">
                <div class="<?= $this->layoutClass('mainbody') ?>">
                    <h2><?= $this->transEsc('Advanced Search') ?></h2>
                    <? /** @var Hebis\View\Helper\Root\SearchTabs $searchTabs */ ?>
                    <? $searchTabsHelper = $this->searchTabs(); ?>
                    <? $handler = $this->controllerName() === "Search" ? "Solr" : $this->controllerName() ?>
                    <? $searchTabs = $searchTabsHelper->getAdvancedTabConfig($handler); ?>
                    <? if (count($searchTabs) > 1) : ?>
                        <br />
                        <ul class="nav nav-tabs">
                            <? foreach($searchTabs as $tab) : ?>
                                <li id="<?=$tab["id"]?>"<?=$tab['selected'] ? ' class="active"' : ''?>>
                                    <a  <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
                                        <?=$this->transEsc($tab['label']); ?>
                                    </a>
                                </li>
                            <? endforeach; ?>
                        </ul>
                    <? endif; ?>
                    <div class="tab-content">
                        <h4><?= $this->transEsc('Search for') ?></h4>
                        <? //$lastSort = $this->searchMemory()->getLastSort($this->searchClassId); ?>
                        <? /*if (!empty($lastSort)): ?>
                            <input type="hidden" name="sort" value="<?= $this->escapeHtmlAttr($lastSort) ?>"/>
                        <? endif;*/ ?>

                        <? /* An empty div. This is the target for the javascript that builds this screen */ ?>
                        <span id="groupPlaceHolder" class="hidden">
                            <span class="hds-icon-plus-circled"></span>
                            <a class="" role="button" href="#" onClick="addGroup()">
                                <?= $this->transEsc('add_search_group') ?>
                            </a>
                        </span>
                        <? /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
                        <div class="no-js">
                            <? if (!empty($this->formOverride)): ?>
                                <?= $this->formOverride ?>
                            <? else: ?>
                                <? for ($group = 0; $group < 3 || $group <= $setGroupCount; $group++): ?>
                                    <? if ($group == 0): ?>
                                        <div id="new_group_template">
                                    <? endif; ?>
                                    <div id="group<?= $group ?>" class="adv-group group well row">
                                        <div class="col-sm-12">
                                            <div class="cancel-icon-container pull-right">
                                                <a href="#" class="help-block group-close hidden" title="<?= $this->transEsc("del_search") ?>">×</a>
                                            </div>
                                        </div>
                                        <div class="col-sm-8" style="padding-right: 0;">
                                            <? for ($search = 0; $search < 3 || (isset($setQueries[$group]) && $search < count($setQueries[$group])); $search++): ?>
                                                <?

                                                if ($group == 0 && $search == 0): ?>
                                                    <div id="new_search_template">
                                                <? endif; ?>
                                                <div id="search<?= $group . '_' . $search ?>" class="adv-search search">
                                                    <div class="row">
                                                        <div class="col-sm-7 left">
                                                            <input name="lookfor<?= $group ?>[]"
                                                                   id="search_lookfor<?= $group . '_' . $search ?>"
                                                                   class="form-control help-searchterm"
                                                                   type="text"<? if (isset($setQueries[$group][$search])): ?> value="<?= $this->escapeHtml($setQueries[$group][$search]->getString()) ?>"<? endif; ?>
                                                                   data-content="<?= $this->transEsc('help.advancedsearch.popover.searchterm')?>"
                                                                   data-placement="top"
                                                                   data-toggle="popover"
                                                                   placeholder="<?= $this->escapeHtmlAttr($this->translate('search terms')) ?>"
                                                                   >
                                                            <div class="help help-header hide">Headline</div>
                                                            <div class="help help-content hide">Content</div>

                                                        </div>
                                                        <div class="col-sm-4 middle">
                                                            <select class="type form-control help-type"
                                                                    name="type<?= $group ?>[]"
                                                                    data-content="<?= $this->transEsc('help.advancedsearch.popover.type')?>">
                                                                <? foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
                                                                    <option value="<?= $this->escapeHtml($searchVal) ?>"<? if (isset($setQueries[$group][$search]) && $searchVal == $setQueries[$group][$search]->getHandler()): ?> selected<? endif; ?>><?= $this->transEsc($searchDesc) ?></option>
                                                                <? endforeach; ?>
                                                            </select>
                                                        </div>
                                                        <div class="col-sm-1 close hidden">
                                                            <a class="help-block" href="#">&times;</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <? if ($group == 0 && $search == 0): ?>
                                                    </div>
                                                    <div class="search_place_holder hidden">
                                                        <span class="hds-icon-plus-circled "></span>
                                                        <a href="#" class="add_search_link hidden"><?= $this->transEsc("add_search") ?></a>
                                                    </div>
                                                <? endif; ?>
                                            <? endfor; ?>

                                        </div>
                                        <div class="col-sm-4 adv-group-match match" style="padding-left: 0; margin-left: 0;">
                                            <div class="form-group">
                                                <label class="col-sm-6 search_bool text-right"><span><?= $this->transEsc("search_match") ?></span></label>
                                                <div class="col-sm-6">
                                                    <select name="bool<?= $group ?>[]" id="search_bool<?= $group ?>"
                                                            class="form-control help-bool"
                                                            data-content="<?= ($this->transEsc('help.advancedsearch.popover.bool')) ?>">
                                                        <option value="AND"<? if (isset($setSearchGroups[$group]) && 'AND' == $setSearchGroups[$group]): ?> selected<? endif; ?>><?= $this->transEsc("search_AND") ?></option>
                                                        <option value="OR"<? if (isset($setSearchGroups[$group]) && 'OR' == $setSearchGroups[$group]): ?> selected<? endif; ?>><?= $this->transEsc("search_OR") ?></option>
                                                        <option value="NOT"<? if (isset($setSearchGroups[$group]) && 'NOT' == $setSearchGroups[$group]): ?> selected<? endif; ?>><?= $this->transEsc("search_NOT") ?></option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <? if ($group == 0): ?>
                                        </div>
                                    <? endif; ?>
                                <? endfor; ?>
                            <? endif; ?>
                        </div>

                        <div class="clearfix">
                            <div id="groupJoin" class="form-inline flip text-center" >
                                <div class="group-join-container">
                                    <div>
                                        <label for="groupJoinOptions"><?= $this->transEsc("search_match") ?>:</label>
                                        <select id="groupJoinOptions"
                                                name="join"
                                                class="form-control help-join"
                                                data-content="help.advancedsearch.popover.join">
                                            <option value="AND"<? if ($searchDetails && $searchDetails->getOperator() == 'ALL'): ?> selected<? endif ?>><?= $this->transEsc('group_AND') ?></option>
                                            <option value="OR"<? if ($searchDetails && $searchDetails->getOperator() == 'OR'): ?> selected<? endif ?>><?= $this->transEsc('group_OR') ?></option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"><br /><br /><!-- --></div>
                        <? if (isset($this->extraAdvancedControls)): ?>
                            <?= $this->extraAdvancedControls ?>
                            <div class="pull-right">
                                <div class="btn-group" role="group">
                                    <button class="btn btn-primary pull-right flip" type="submit"><span
                                                class="hds-icon-search"></span> <?= $this->transEsc('Find') ?></button>
                                    <button class="btn btn-default pull-right clear-btn" type="button"><span
                                                class="hds-icon-recycle"></span><?= $this->transEsc('Clear') ?></button>
                                </div>
                            </div>
                        <? endif; ?>
                    </div>
                    <!--
                    <div class="pull-right">
                        <div class="btn-group" role="group">
                            <button class="btn btn-primary pull-right flip" type="submit"><span
                                        class="hds-icon-search"></span> <?= $this->transEsc('Find') ?></button>
                            <button class="btn btn-default pull-right clear-btn" type="button"><span
                                        class="hds-icon-recycle"></span><?= $this->transEsc('Clear') ?></button>
                        </div>
                    </div>
                    -->

                </div>

                <div class="<?= $this->layoutClass('sidebar') ?>">
                    <? if ($hasDefaultsApplied): ?>
                        <input type="hidden" name="dfApplied" value="1"/>
                    <? endif ?>
                    <div class="sidegroup">
                        <h4><?= $this->transEsc("Search Tips") ?></h4>
                        <div class="list-group">
                            <a class="list-group-item help-link" data-lightbox
                               href="<?= $this->url('help-home') ?>?topic=advsearch"><?= $this->transEsc("Help with Advanced Search") ?></a>
                            <a class="list-group-item help-link" data-lightbox
                               href="<?= $this->url('help-home') ?>?topic=search"><?= $this->transEsc("Help with Search Operators") ?></a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
