<? if (isset($this->ranges) && !empty($this->ranges)): ?>
<br /><br />
    <? $params = $this->searchParams($this->searchClassId);
    $params->activateAllFacets(); ?>
    <? foreach ($this->ranges as $current): $escField = $this->escapeHtmlAttr($current['field']); ?>
        <? $extraInputAttribs = ($current['type'] == 'date') ? 'maxlength="4" ' : ''; ?>

        <label><?= $this->translate($params->getFacetLabel($current['field'])) ?></label>
        <input type="hidden" name="<?= $this->escapeHtmlAttr($current['type']) ?>range[]" value="<?= $escField ?>"/>
        <? if ($current['type'] == 'date'): ?>
            <div class="row">
                <div class="col-sm-12">
                    <div class="slider-container">
                        <? $sliderId = $escField . $this->escapeHtmlAttr($current['type']) . 'Slider'; ?>
                        <input type="text" id="<?= $sliderId ?>">
                    </div>
                    <br />
                    <?
                    $current['values'][0] = substr($current['values'][0], 0, 4);
                    $current['values'][1] = substr($current['values'][1], 0, 4);
                    $this->headScript()->appendFile('vendor/bootstrap-slider.js');
                    $min = !empty($current['values'][0]) ? min($current['values'][0], 0) : 0;
                    $future = date('Y', time() + 31536000);
                    $max = !empty($current['values'][1]) ? max($future, $current['values'][1]) : $future;
                    $low = !empty($current['values'][0]) && intval($current['values'][0]) > $min ? $current['values'][0] : $min;
                    $high = !empty($current['values'][1]) && intval($current['values'][1]) < $max ? $current['values'][1] : $max;
                    $min = intval($min);
                    $max = intval($max);
                    $low = intval($low);
                    $high = intval($high);
                    $reversed = $this->layout()->rtl ? 'true' : 'false';
                    $init = !empty($current['values'][0]) ? 'fillTexts()' : '';
                    $half = floor($min+(($max-$min)/2));
                    $quarter = floor($half+(($max-$min)/2)/2);
                    $halfquarter = floor($quarter+((($max-$min)/2)/2)/1.5);
                    $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
    var v = {$sliderId}.getValue();
    $('#${escField}from').val(v[0]);
    $('#${escField}to').val(v[1]);
  };
  var {$sliderId} = $('#{$sliderId}')
    .slider({
'min':{$min},
       'max':{$max},
       'handle':"square",
       'tooltip':"hide",
       'value':[{$low},{$high}],
         'ticks':[{$min}, {$half}, {$quarter}, {$halfquarter}, {$high}],
	     'ticks_labels':[{$min}, {$half}, {$quarter}, {$halfquarter}, {$high}],
	     'ticks_positions':[0, 25, 50, 75, 100],
       'reversed': {$reversed}
    })
    .on('change', fillTexts)
    .data('slider');
  {$init}
  $('form button:reset').click(function (event) {
      
      $('#{$sliderId}').slider('refresh');
  });
     $("#advSearchForm").submit(function(e) {
        if ($('#publish_datefrom').val() != "") {
            $('#publish_datefrom').val(toIso($('#publish_datefrom').val()));    
        }
        if ($('#publish_dateto').val() != "") {
            $('#publish_dateto').val(toIso($('#publish_dateto').val()));
        }
        return true;
  });
  
});
JS;
            ?>
                </div> <!-- /.col-sm-12 -->
            </div> <!-- /.row -->
            <div class="row">
                <?= $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
                <div class="col-sm-6 col-md-offset-4 col-md-2">
                    <label for="<?= $escField ?>from" class="sr-only"><?= $this->transEsc('date_from') ?>:</label>
                    <input type="text" name="<?= $escField ?>from" id="<?= $escField ?>from"
                           value="<?= isset($current['values'][0]) ? $this->escapeHtmlAttr($current['values'][0]) : '' ?>"
                           class="form-control" <?= $extraInputAttribs ?>/>
                </div>
                <div class="col-sm-6 col-md-2">
                    <label for="<?= $escField ?>to" class="sr-only"><?= $this->transEsc('date_to') ?>:</label>
                    <input type="text" name="<?= $escField ?>to" id="<?= $escField ?>to"
                           value="<?= isset($current['values'][1]) ? $this->escapeHtmlAttr($current['values'][1]) : '' ?>"
                           class="form-control" <?= $extraInputAttribs ?>/>
                </div>
            </div>
        <? endif; ?>
    <? endforeach; ?>
<? endif; ?>
