<? $this->headLink()->appendStylesheet('EDS.css'); ?>
<?
    $items = $this->driver->getItems();
    $dbLabel = $this->driver->getDbLabel();
    $thumb = $this->driver->getThumbnail('medium');
    $pubType = $this->driver->getPubType();
    $customLinks = $this->driver->getCustomLinks();
    $accessLevel = $this->driver->getAccessLevel();
    $restrictedView = empty($accessLevel) ? false : true;
    $abstract = null;
?>

<?
$rediLinks =
'$(document).ready(function(){
    var url = VuFind.path + "/EdsRecord/redilink?id='.$this->driver->getUniqueId().'";
    $.get(url, function (d) {
        $("#redi").append(d);
    });
});';
$this->headScript()->appendScript($rediLinks); ?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3 img-col">
      <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
          <ul class="pager hidden-print hidden-xs hidden-sm">
              <? if ($this->scrollData['previousRecord']): ?>
                  <li>
                      <a href="<?= $this->recordLink()->getUrl($this->scrollData['previousRecord']) ?>"
                         title="<?= $this->transEsc('Previous Search Result') ?>"><span class="hds-icon-left-open"><!-- --> </span><span class="sr-only"><?= $this->transEsc('Prev') ?></span></a>
                  </li>
              <? else: ?>
                  <li class="disabled"><span class="hds-icon-left-open"><!-- --> </span><span class="sr-only"><?= $this->transEsc('Prev') ?></span></li>
              <? endif; ?>
              <li><span><?= $this->localizedNumber($this->scrollData['currentPosition']) . ' / ' . $this->localizedNumber($this->scrollData['resultTotal']) //' ' . $this->transEsc('results') ?></span></li>
              <? if ($this->scrollData['nextRecord']): ?>
                  <li>
                      <a href="<?= $this->recordLink()->getUrl($this->scrollData['nextRecord']) ?>"
                         title="<?= $this->transEsc('Next Search Result') ?>"><span class="sr-only"><?= $this->transEsc('Next') ?></span><span class="hds-icon-right-open"> <!-- --></span></a>
                  </li>
              <? else: ?>
                  <li class="disabled"><span class="sr-only"><?= $this->transEsc('Next') ?></span><span class="hds-icon-right-open"> <!-- --></span></li>
              <? endif; ?>
          </ul>
      <? endif; ?>

    <? if ($thumb): ?>
        <img src="<?=$this->escapeHtmlAttr($thumb)?>" class="recordcover" alt="<?=$this->transEsc('Cover Image')?>"/>
    <? else: ?>
      <div class="clearfix">
        <span class="recordcover pt-icon pt-<?=$this->driver->getPubTypeId()?>"></span>
      </div>
    <? endif; ?>
    <? if ($pubType): ?>
      <p><?=$this->transEsc($pubType)?></p>
    <? endif; ?>

    <div class="external-links">
      <? $pdfLink = $this->driver->getPdfLink();
          if ($pdfLink): ?>
        <span>
          <a href="<?=$pdfLink?>" class="icon pdf fulltext">
            <?=$this->transEsc('PDF Full Text')?>
          </a>
        </span><br />
      <? endif; ?>
      <? if ($this->driver->hasHTMLFullTextAvailable()): ?>
        <span>
          <a href="<?=$this->recordLink()->getUrl($this->driver, 'fulltext')?>#html" class="icon html fulltext">
            <?=$this->transEsc('HTML Full Text')?>
          </a>
        </span><br />
      <? endif; ?>
    </div>
    <div id="redi"><!-- --></div>
  </div>
  <div class="col-sm-9 info-col">
    <h3 property="name"><?=$this->escapeHtml($this->driver->getTitle())?></h3>

    <!--<table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">-->
      <div class="record-details">
      <? foreach ($items as $key => $item): ?>
          <? if ($item['Group'] == "Ab") : ?>
            <? $abstract = $item; ?>
          <? elseif (!empty($item['Data'])): ?>
            <div class="row">
                <div class="bold col-sm-12 col-md-3 col-lg-2">
                    <?=$this->escapeHtml($item['Label'])?>:
                </div>
                <div class="col-sm-12 col-md-9 col-lg-10">
                    <?=$this->driver->linkUrls($item['Data'])?>
                </div>
            </div>
        <? endif; ?>
      <? endforeach; ?>

      <? if ($dbLabel): ?>
        <div class="row">
          <div class="bold col-sm-12 col-md-3 col-lg-2"><?=$this->transEsc('Database')?>:</div>
            <div class="col-sm-12 col-md-9 col-lg-10"><?=$this->escapeHtml($dbLabel)?></div>
        </div>
      <? endif; ?>
      <? $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
      if (!empty($customLinks)): ?>
          <br />
          <h4><?= $this->transEsc('Links'); ?></h4>
          <div class="resultItemLine4 custom-links">
          <? foreach ($customLinks as $customLink): ?>
              <? $url = isset($customLink['Url']) ? $customLink['Url'] : '';
              $mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
              $icon = isset ($customLink['Icon']) ? $customLink['Icon'] : '';
              $name = isset($customLink['Text']) ? $customLink['Text'] : '';
              ?>
              <span>
                <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$this->escapeHtmlAttr($mot)?>" class="custom-link">
                    <? if ($icon): ?><img src="<?=$this->escapeHtmlAttr($icon)?>" /> <? endif; ?><?=$this->escapeHtml($name)?>
                </a>
            </span>
          <? endforeach; ?>
          </div>
      <? endif; ?>
        <? if ($this->driver->hasHTMLFullTextAvailable() || !empty($abstract)) : ?>
            <br />
            <h4><?= $this->transEsc('Further Information'); ?></h4>
          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <? if (!empty($abstract) && !empty($abstract['Data'])) : ?>
                  <div class="panel panel-default">
                      <div class="panel-heading" role="tab" id="headingAbstract">
                          <h4 class="panel-title">
                              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseAbstract" aria-controls="collapseAbstract"><?=$this->transEsc('Abstract')?></a>
                          </h4>
                      </div>
                      <div id="collapseAbstract" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingAbstract">
                          <div class="panel-body">
                              <div class="col-sm-12 col-md-9 col-lg-10">
                                  <?=$this->driver->linkUrls($abstract['Data'])?>
                              </div>
                          </div>
                      </div>
                  </div>
              <? endif; ?>
              <? if ($this->driver->hasHTMLFullTextAvailable()): ?>
              <div class="panel panel-default">
                  <div class="panel-heading" role="tab" id="headingOne">
                      <h4 class="panel-title">
                          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-controls="collapseOne"><?=$this->transEsc('Fulltext')?></a>
                      </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <? if (!$restrictedView) : ?>
                                <? $fullText = $this->driver->getHtmlFullText(); ?>
                                <?=$fullText?>
                            <? else : ?>
                                <p><?=$this->transEsc('Full text is not displayed to guests')?></p>
                                <a class="login" href="<?=$this->url('myresearch-home')?>" rel="nofollow">
                                    <strong><?=$this->transEsc('Login for full access')?></strong>
                                </a>
                            <?endif; ?>
                      </div>
                  </div>
              </div>
              <? endif; ?>
          </div>
        <? endif; ?>
    <!-- </table>-->


  </div>
</div>
