<?php
$this->headTitle($this->translate('VuFind Administration - Add Custom Page'));
?>

<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">

        <h3><?= $this->translate('➕ Add New Page') ?></h3>

        <div class="form-group">
            <form>
                <textarea id="headline" rows="1" style="width: 300px; font-variant: full-width">Headline</textarea>
                <textarea id="content" style="width: 700px; height: 300px">Content!</textarea>
            </form>

        </div>

    </div>

    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>

<!--WYSIWYG Script-->
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">
    bkLib.onDomLoaded(function () {
        nicEditors.editors.push(
            new nicEditor().panelInstance(
                document.getElementById('content')));
    });
</script>
