<?
// Set page title.
$this->headTitle($this->translate('VuFind Administration - Custom Pages / DEL'));

?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h1 style="background-color: red; color: white">DELETE Custom Page</h1>
        <p>Sicher? J/N</p>


    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
