<div class="list-group">
    <a href="<?= $this->url('admin') ?>"
       class="list-group-item<?= strtolower($this->layout()->templateName) == "home" ? ' active' : '' ?>"><?= $this->transEsc('Home') ?></a>
    <a href="<?= $this->url('admin/social') ?>"
       class="list-group-item<?= strtolower($this->layout()->templateName) == "socialstats" ? ' active' : '' ?>"><?= $this->transEsc('Social Statistics') ?></a>
    <a href="<?= $this->url('admin/statistics') ?>"
       class="list-group-item<?= strtolower($this->layout()->templateName) == "statistics" ? ' active' : '' ?>"><?= $this->transEsc('Statistics') ?></a>
    <a href="<?= $this->url('admin/config') ?>"
       class="list-group-item<?= strtolower($this->layout()->templateName) == "config" ? ' active' : '' ?>"><?= $this->transEsc('Configuration') ?></a>
    <a href="<?= $this->url('admin/maintenance') ?>"
       class="list-group-item<?= strtolower($this->layout()->templateName) == "maintenance" ? ' active' : '' ?>"><?= $this->transEsc('System Maintenance') ?></a>
    <a href="<?= $this->url('admin/tags') ?>"
       class="list-group-item<?= strtolower($this->layout()->templateName) == "tags" ? ' active' : '' ?>"><?= $this->transEsc('Tag Maintenance') ?></a>
    <a href="<?= $this->url('adminlogs') ?>"
       class="list-group-item<?= strtolower($this->layout()->templateName) == "logs" ? ' active' : '' ?>"><?= $this->transEsc('Logs') ?></a>
    <a href="<?= $this->url('broadcastadmin', ['action' => 'bchome']) ?>"<? $templateBroadcast = in_array(strtolower($this->layout()->templateName), array('bc-home', 'bc-add', 'bc-preview', 'bc-edit')); ?>
       class="list-group-item<?= $templateBroadcast ? ' active' : '' ?>"><?= $this->transEsc('Broadcasts') ?></a>
    <a href="<?= $this->url('pageadmin') ?>"<? $templateStaticPages = in_array(strtolower($this->layout()->templateName), array('list', 'add', 'view', 'edit', 'delete')); ?>
       class="list-group-item<?= $templateStaticPages ? ' active' : '' ?>"><?= $this->transEsc('Static Pages') ?></a>
</div>
