<?
if ($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
} else {
    $user_id = false;
}
?>

<div class="row">

    <div class="col-md-9<?// $this->layoutClass('mainbody') ?>">

        <? $format = $this->physicalDescriptionFormat($this->driver);//$this->driver->getFormats(); if (!empty($formats)): ?>
        <div vocab="http://schema.org/" resource="#record" typeof="<?= $this->driver->getSchemaOrgFormats() ?> Product">

            <div class="row">
                <div class="col-sm-3 hidden-xs">
                    <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
                        <ul class="pager hidden-print hidden-xs hidden-sm">
                            <? if ($this->scrollData['previousRecord']): ?>
                                <li>
                                    <a href="<?= $this->recordLink()->getUrl($this->scrollData['previousRecord']) ?>"
                                       title="<?= $this->translate('Previous Search Result') ?>"><span class="hds-icon-left-open"><!-- --> </span><span class="sr-only"><?= $this->translate('Prev') ?></span></a>
                                </li>
                            <? else: ?>
                                <li class="disabled"><span class="hds-icon-left-open"><!-- --> </span><span class="sr-only"><?= $this->translate('Prev') ?></span></li>
                            <? endif; ?>
                            <li><span><?= $this->localizedNumber($this->scrollData['currentPosition']) . ' / ' . $this->localizedNumber($this->scrollData['resultTotal']) //' ' . $this->translate('results') ?></span></li>
                            <? if ($this->scrollData['nextRecord']): ?>
                                <li>
                                    <a href="<?= $this->recordLink()->getUrl($this->scrollData['nextRecord']) ?>"
                                       title="<?= $this->translate('Next Search Result') ?>"><span class="sr-only"><?= $this->translate('Next') ?></span><span class="hds-icon-right-open"> <!-- --></span></a>
                                </li>
                            <? else: ?>
                                <li class="disabled"><span class="sr-only"><?= $this->translate('Next') ?></span><span class="hds-icon-right-open"> <!-- --></span></li>
                            <? endif; ?>
                        </ul>
                    <? endif; ?>
                    <div class="text-center">
                        <? $cached = $this->record($this->driver)->hasThumbnailCachedFile('medium'); ?>

                        <? /* Display thumbnail if appropriate: */ ?>
                        <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium');
                        $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
                        <? if ($mediumThumb): ?>
                            <? if ($largeThumb): ?><a href="<?= $this->escapeHtmlAttr($largeThumb) ?>"><? endif; ?>
                            <img alt="<?= $this->translate('Cover Image') ?>" class="img-thumbnail img-responsive"
                                 src="<?= $this->escapeHtmlAttr($mediumThumb); ?>"/>
                            <? if ($largeThumb): ?></a><? endif; ?>
                        <? else: ?>
                            <img src="<?= $this->url('cover-unavailable') ?>" class="img-responsive"
                                 alt="<?= $this->translate('No Cover Image') ?>"/>
                        <? endif; ?>
                    </div>
                    <? $multipartViewHelper = $this->multiPartItems($this->driver);
                    if ($multipartViewHelper->isMultipartItem() && !empty($multipartItem = $multipartViewHelper->renderShowAllVolumesLink())) : ?>
                        <br />
                        <div class="text-center multipartItems">
                            <span class="hds-icon-list-bullet"> <? echo $multipartItem; ?></span>
                        </div>
                    <? endif; ?>
                </div>
                <div class="col-sm-9">
                    <h3 property="name">
                        <? //$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?>
                        <span class="hds-icon-<?= $format ?>"></span>
                        <?= $this->escapeHtml($this->singleRecordTitleStatementHeadline($this->driver)) ?>
                    </h3>

                    <? $summary = $this->driver->getSummary();
                    $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
                    <? if ($summary): ?>
                        <p><?= $this->truncate($summary, 300) ?></p>

                        <? if (strlen($summary) > 300): ?>
                            <p>
                                <a href='<?= $this->recordLink()->getTabUrl($this->driver, 'Description') ?>#tabnav'><?= $this->translate('Full description') ?></a>
                            </p>
                        <? endif; ?>
                    <? endif; ?>

                    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
                        <? /* Display the lists that this record is saved to */ ?>
                        <div class="savedLists hidden alert alert-info" id="savedLists">
                            <strong><?= $this->translate("Saved in") ?>:</strong>
                        </div>
                    <? endif; ?>

                    <? /* Display Main Details */ ?>
                    <div class="record-details">

                        <!-- Titel -->
                        <? $title = $this->singleRecordTitleStatement($this->driver); ?>
                        <? $owtitle = $this->singleRecordOWTitleStatement($this->driver); //get the ow title from view helper ?>
                        <div class="row">
                            <div class="bold col-sm-12 col-md-3 col-lg-2">
                                <?= $this->translate('Title') ?>:
                            </div>
                            <div class="col-sm-12 col-md-9 col-lg-10">
                                <? if ($owtitle) : ?><?= $owtitle ?><br/><? endif; ?>
                                <bdi><?= $title ?></bdi>
                            </div>
                        </div>

                        <!-- Unterreihe -->
                        <? $sectionOfWork = $this->singleRecordSectionOfAWork($this->driver); ?>
                        <? if ($sectionOfWork) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Section of a work'); ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><bdi><?= $sectionOfWork ?></bdi></div>
                            </div>
                        <? endif; ?>

                        <!-- Teil -->
                        <? $partOfWork = $this->singleRecordPartOfAWork($this->driver); ?>
                        <? if ($partOfWork) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Part of a work'); ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><bdi><?= $partOfWork ?></bdi></div>
                            </div>
                        <? endif; ?>

                        <!-- Verantwortlich -->
                        <? $authors = $this->singleRecordPersonalName($this->driver, false); ?>
                        <? $owauthors = $this->singleRecordOWPersonalName($this->driver, false); ?>
                        <? if (!empty($authors)) : ?>
                            <div class="row">
                                <div
                                    class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Author/editor-in-chief') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10" property="author">
                                    <? if (!empty($owauthors)) : ?><?= $owauthors ?><br/><? endif; ?>
                                    <bdi><?= $authors ?></bdi>
                                </div>
                            </div>
                        <? endif; ?>

                        <!-- Körperschaft -->
                        <? $corporate = $this->singleRecordCorporateName($this->driver); ?>
                        <? if (!empty($corporate)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Corporate') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10" property="author">
                                    <a href="<?= $this->record($this->driver)->getLink('other', html_entity_decode($corporate)); ?>"><?= $corporate ?></a>
                                </div>
                            </div>
                        <? endif; ?>


                        <? $hostItem = $this->singleRecordHostItemEntry($this->driver); ?>
                        <? if (!empty($hostItem)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Published in') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10">
                                    <?= $this->singleRecordHostItemEntry($this->driver); ?>
                                </div>
                            </div>
                        <? endif; ?>

                        <? $datesOfPublication = $this->singleRecordDatesOfPublicationSequentialDesignation($this->driver); ?>
                        <? if (!empty($datesOfPublication)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Dates of publication/Sequential designation'); ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $datesOfPublication ?></div>
                            </div>
                        <? endif; ?>


                        <!-- Published in
                    <? //$marcJournal = $this->singleRecordMarcJournal($this->driver); ?>
                    <? if ($marcJournal) : ?>
                        <div class="row">
                            <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('Marc Journal') ?>:</div>
                            <div class="col-sm-12 col-md-9 col-lg-10"><?= $marcJournal ?></div>
                        </div>
                    <? endif; ?>
                    -->

                        <!-- Manufacture / Entstehung-->
                        <? $manufacture = $this->singleRecordManufacture($this->driver); ?>
                        <? if (!empty($manufacture)) : ?>
                            <div class="row">
                                <div
                                    class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Manufacture'); ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><bdi><?= $manufacture ?></bdi></div>
                            </div>
                        <? endif; ?>


                        <!-- Publication / Veröffentlicht -->
                        <? $publicationDistribution = $this->singleRecordPublication($this->driver); ?>
                        <? $publicationOWDistribution = $this->singleRecordOWPublication($this->driver); ?>
                        <? if (!empty($publicationDistribution)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Publication') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10">
                                    <? if (!empty($publicationOWDistribution)) : ?>
                                        <?= $publicationOWDistribution ?><br/>
                                    <? endif; ?>
                                    <bdi><?= $publicationDistribution ?></bdi>
                                </div>
                            </div>
                        <? endif; ?>

                        <? $yearOfPublication = $this->singleRecordPublicationYear($this->driver); ?>
                        <? if (!empty($yearOfPublication)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Year of Publication'); ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $yearOfPublication ?></div>
                            </div>
                        <? endif; ?>

                        <!-- Production / Herstellung -->
                        <? $production = $this->singleRecordProduction($this->driver); ?>
                        <? if (!empty($production)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Production') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $production ?></div>
                            </div>
                        <? endif; ?>

                        <!-- Distribution / Vertrieb -->
                        <? $distribution = $this->singleRecordDistribution($this->driver); ?>
                        <? if (!empty($distribution)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Distribution') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $distribution ?></div>
                            </div>
                        <? endif; ?>

                        <!-- Einheitssachtitel -->
                        <? $uniformTitle = $this->singleRecordUniformTitle($this->driver); ?>
                        <? if (!empty($uniformTitle)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Uniform title') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $uniformTitle ?></div>
                            </div>
                        <? endif; ?>

                        <!-- auch als -->
                        <? $additionalPhysical = $this->singleRecordAdditionalPhysicalFromAvailableNote($this->driver); ?>
                        <? if (!empty($additionalPhysical)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('Additional physical from available note') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><bdi><?= $additionalPhysical ?></bdi></div>
                            </div>
                        <? endif; ?>

                        <!-- Reproduction note / Vorliegende Ausgabe -->
                        <? $reproduction = $this->singleRecordReproductionNote($this->driver); ?>
                        <? if (!empty($reproduction)) : ?>
                            <div class="row">
                                <div
                                    class="bold col-sm-12 col-md-3 col-lg-2" property="bookEdition"><?= $this->translate('Reproduction note') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $reproduction ?></div>
                            </div>
                        <? endif; ?>

                        <!-- Hochschulschrift -->
                        <? $dissertationNote = $this->singleRecordDissertationNote($this->driver) ?>
                        <? if (!empty($dissertationNote)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Dissertation note') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $dissertationNote ?></div>
                            </div>
                        <? endif; ?>

                        <? $nextTitles = $this->driver->getNewerTitles();
                        $prevTitles = $this->driver->getPreviousTitles(); ?>
                        <? if (!empty($nextTitles)): ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('New Title') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10">
                                    <? foreach ($nextTitles as $field): ?>
                                        <a href="<?= $this->record($this->driver)->getLink('title', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                                        <br/>
                                    <? endforeach; ?>
                                </div>
                            </div>
                        <? endif; ?>

                        <? if (!empty($prevTitles)): ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Previous Title') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10">
                                    <? foreach ($prevTitles as $field): ?>
                                        <a href="<?= $this->record($this->driver)->getLink('title', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                                        <br/>
                                    <? endforeach; ?>
                                </div>
                            </div>
                        <? endif; ?>

                        <!-- Other Edition Entry-->
                        <? $otherEditionEntry = $this->singleRecordOtherEditionEntry($this->driver); ?>
                        <? if (!empty($otherEditionEntry)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Other edition entry') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><bdi><?= $otherEditionEntry ?></bdi></div>
                            </div>
                        <? endif; ?>

                        <!-- Title Contains -->
                        <? $titleContains = $this->singleRecordTitleContains($this->driver); ?>
                        <? if (!empty($titleContains)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Title contains'); ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $titleContains ?></div>
                            </div>
                        <? endif; ?>

                        <!-- ISBN -->
                        <? $isbn = $this->singleRecordInternationalStandardBookNumber($this->driver); ?>
                        <? if (!empty($isbn)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('ISBN') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $isbn ?></div>
                            </div>
                        <? endif; ?>

                        <!-- ISSN -->
                        <? $issn = $this->singleRecordInternationalStandardSerialNumber($this->driver); ?>
                        <? if (!empty($issn)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('ISSN') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $issn ?></div>
                            </div>
                        <? endif; ?>

                        <!-- ISMN -->
                        <? $ismn = $this->singleRecordInternationalStandardMusicNumber($this->driver); ?>
                        <? if (!empty($ismn)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('ISMN') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $ismn ?></div>
                            </div>
                        <? endif; ?>

                        <!-- Physical Description / Umfang -->
                        <? $physicalDescription = $this->singleRecordPhysicalDescription($this->driver); ?>
                        <? if (!empty($physicalDescription)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Physical description scale') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><bdi><?= $physicalDescription ?></bdi></div>
                            </div>
                        <? endif; ?>

                        <? if (!empty($format)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('Format') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><span
                                        class="label label-info hds-icon-<?= $format ?>">
                                    <?= $this->translate($format); ?>
                                </span></div>
                            </div>
                        <? endif; ?>

                        <? $langs = $this->driver->getLanguages();
                        if (!empty($langs)): ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('Language') ?>:</div>
                                <div
                                    class="col-sm-12 col-md-9 col-lg-10"><? foreach ($langs as $lang): ?><?= $this->translate($lang) ?>
                                        <br/><? endforeach; ?></div>
                            </div>
                        <? endif; ?>

                        <!-- RVK -->
                        <? $rvk = $this->singleRecordOtherClassificationNumber($this->driver, true) ?>
                        <? if (!empty($rvk)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('RVK-Notation'); ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10">
                                    <? foreach ($rvk as $r) : ?>
                                        <? $rvkId = str_replace(" ", "-", $r); ?>
                                        <span class="rvk-info">
                                            <a class="rvk-link"
                                               href="<?= $this->basePath() ?>/Search/Results?lookfor=rvk_full%3A%22<?= $this->transEsc($r) ?>%22&type=allfields"><?= $this->translate($r) ?></a>&nbsp
                                            <span
                                                role="button"
                                                style="padding-bottom: 1px; font-size: 80%; font-weight: lighter; cursor: pointer"
                                                data-id="<?= $r ?>"
                                                data-container="body"
                                                data-popover-content="#rvk_<?= $rvkId ?>"
                                                class="rvk_popover label label-info">rvk</span>
                                        </span>
                                        <div class="hidden" id="rvk_<?= $rvkId ?>"><div class="popover-heading"></div><div class="popover-body"></div></div>
                                        &nbsp;&nbsp;
                                    <? endforeach; ?>
                                </div>
                            </div>
                        <? endif; ?>


                        <!-- Schlagworte -->
                        <? $keywords = $this->singleRecordSubjectAccessFieldsGeneralInformation($this->driver) ?>
                        <? if (!empty($keywords)) : ?>
                            <div class="row">
                                <div
                                    class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('Subject Added Keywords'); ?></div>
                                <div class="col-sm-12 col-md-9 col-lg-10">
                                    <div class="keywords">
                                        <form method="get" action="<?= $this->basePath() ?>/Search/Results"
                                              id="searchForm" name="searchForm" class="search">
                                            <input type="hidden" name="bool0[]" value="AND"/>
                                            <?= str_replace("<br />", " ", $keywords); ?>
                                            <button type="submit" class="btn btn-default btn-xs">
                                                <span class="hds-icon-search"></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        <? endif; ?>

                        <!-- Preceding Entry / Succeeding Entry -->
                        <? $precedingSucceeding = $this->singleRecordPrecedingSucceedingEntry($this->driver); ?>
                        <? if (!empty($precedingSucceeding)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2">
                                    <?= $this->translate('Preceding entry/Succeeding entry') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $precedingSucceeding ?></div>
                            </div>
                        <? endif; ?>

                        <? /* Display series section if at least one series exists. */ ?>
                        <? //$series = $this->singleRecordSeriesStatementAddedEntry($this->driver); ?>
                        <? $multipartViewHelper = $this->multiPartItems($this->driver); ?>
                        <? $parent = $multipartViewHelper->renderParentalItem(); ?>
                        <? if (!empty($parent)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('series_multipart') ?>:</div>
                                <div class="col-sm-12 col-md-9 col-lg-10">
                                    <?= $parent ?>
                                    <br />
                                    <?= $multipartViewHelper->renderShowAllVolumesLink(); ?>
                                </div>
                            </div>
                        <? endif; ?>

                        <!-- Zielgruppe -->
                        <? $targetAudience = $this->singleRecordTargetAudienceNote($this->driver); ?>
                        <? if (!empty($targetAudience)) : ?>
                            <div class="row">
                                <div class="bold col-sm-12 col-md-3 col-lg-2"><?= $this->translate('Zielgruppe') ?>:
                                </div>
                                <div class="col-sm-12 col-md-9 col-lg-10"><?= $targetAudience ?></div>
                            </div>
                        <? endif; ?>
                    </div> <!-- /.record-details -->
                    <!--
                    <table>

                        <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount');
                        if ($childRecordCount): ?>
                            <tr>
                                <th><?= $this->translate('child_records') ?>:</th>
                                <td>
                                    <a href="<?= $this->recordLink()->getChildRecordSearchUrl($this->driver) ?>"><?= $this->translate('child_record_count', array('%%count%%' => $childRecordCount)) ?></a>
                                </td>
                            </tr>
                        <? endif; ?>


                        <?
                        //$openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
                        // Account for replace_other_urls setting
                        $urls = $this->record($this->driver)->getLinkDetails();
                        ?>
                        <? /* if (!empty($urls)): ?>
                            <tr>
                                <th><?= $this->translate('Online Access') ?>:</th>
                                <td>
                                    <? foreach ($urls as $current): ?>
                                        <a href="<?= $this->escapeHtmlAttr($this->proxyUrl($current['url'])) ?>"><?= $this->escapeHtml($current['desc']) ?></a>
                                        <br/>
                                    <? endforeach; ?>
                                </td>
                            </tr>
                        <? endif; */ ?>

                        <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
                        <? if (!empty($recordLinks)): ?>
                            <tr>
                                <th><?= $this->translate('Related Items') ?>:</th>
                                <td>
                                    <? foreach ($recordLinks as $recordLink): ?>
                                        <?= $this->translate($recordLink['title']) ?>:
                                        <a href="<?= $this->recordLink()->related($recordLink['link']) ?>"><?= $this->escapeHtml($recordLink['value']) ?></a>
                                        <br/>
                                    <? endforeach; ?>
                                    <? /* if we have record links, display relevant explanatory notes */
                                    $related = $this->driver->getRelationshipNotes();
                                    if (!empty($related)): ?>
                                        <? foreach ($related as $field): ?>
                                            <?= $this->escapeHtml($field) ?><br/>
                                        <? endforeach; ?>
                                    <? endif; ?>

                                    <?= $this->bibTip($this->driver); ?>
                                </td>
                            </tr>
                        <? endif; ?>

                        <? if ($this->usertags()->getMode() !== 'disabled'): ?>
                            <? $tagList = $this->driver->getTags(); ?>
                            <tr>
                                <th><?= $this->translate('Tags') ?>:</th>
                                <td>
                                    <a class="tag-record btn btn-link pull-right flip"
                                       href="<?= $this->recordLink()->getActionUrl($this->driver, 'AddTag') ?>"
                                       data-lightbox>
                                        <i class="fa fa-plus"></i> <?= $this->translate('Add Tag') ?>
                                    </a>

                                    <span class="pull-right">
                                        <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?= $this->recordLink()->getActionUrl($this->driver, 'AddTag') ?>" title="<?= $this->translate('Add Tag') ?>"><?= $this->translate('Add Tag') ?></a>
                                    </span>

                                    <?= $this->context($this)->renderInContext('record/tagcloud', array('tagList' => $tagList, 'loggedin' => $loggedin)) ?>

                                    <div id="tagList">
                                        <? if (count($tagList) > 0): ?>
                                            <? $i = 0;
                                            foreach ($tagList as $tag): ?><?= ($i++ == 0) ? '' : ', ' ?><a href="<?= $this->url('tag-home') ?>?lookfor=<?= urlencode($tag->tag) ?>"><?= $this->escapeHtml($tag->tag) ?></a> (<?= $this->escapeHtml($tag->cnt) ?>)<? endforeach; ?>
                                        <? else: ?>
                                            <?= $this->translate('No Tags') ?>, <?= $this->translate('Be the first to tag this record') ?>!
                                        <? endif; ?>
                                    </div>

                                </td>
                            </tr>
                        <? endif; ?>
                    </table>
                    -->
                    <? /* End Main Details */ ?>
                </div>
            </div>
        </div>

        <div class="tab-description">
            <? if (count($this->tabs) > 0): ?>
                <a name="tabnav"></a>
                <ul class="recordTabs nav nav-tabs nav-justified">
                    <?
                    /** @var \Hebis\RecordTab\TabInterface $obj */
                    foreach ($this->tabs as $tab => $obj): ?>
                        <? // add current tab to breadcrumbs if applicable:
                        $desc = $obj->getDescription();
                        $hasContents = $obj->hasContents();
                        $tab_classes = array();
                        if (0 === strcasecmp($this->activeTab, $tab)) {
                            $tab_classes[] = 'active';
                            $breadcrumbs = $this->layout()->breadcrumbs .= '<li class="active">' . $this->translate($desc) . '</li>';
                            $activeTabObj = $obj;
                        }
                        if (!$obj->isVisible()) {
                            $tab_classes[] = 'hidden';
                        }
                        if (!$obj->supportsAjax()) {
                            $tab_classes[] = 'noajax';
                        }
                        if (!$hasContents) {
                            $tab_classes[] = 'disabled';
                        }
                        ?>
                        <li<?= count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : '' ?>>
                            <? if ($hasContents) : ?>
                            <a id="<?= strtolower($tab) ?>"
                               href="<?= $this->recordLink()->getTabUrl($this->driver, $tab) ?>#tabnav"><?= $this->translate($desc) ?></a>
                            <? else : ?>
                                <a id="<?= strtolower($tab) ?>" href="#tabnav"><?= $this->translate($desc) ?></a>
                            <? endif; ?>
                        </li>
                    <? endforeach; ?>
                </ul>
            <? endif; ?>

            <div class="tab-content" id="record-tabs">
                <div class="tab-pane active" id="<?= $this->activeTab ?>-tab">
                    <?= isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
                </div>
            </div>
        </div>

        <span class="Z3988" title="<?= $this->escapeHtmlAttr($this->driver->getOpenURL()) ?>"></span>
    </div>
    <div class="col-md-3<? //$this->layoutClass('sidebar') ?>">

        <div class="text-center">


            <? /* Display qrcode if appropriate: */ ?>
            <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
            <? if ($QRCode): ?>
                <span class="hidden-xs">
                  <br/><img alt="<?= $this->translate('QR Code') ?>" class="qrcode"
                            src="<?= $this->escapeHtmlAttr($QRCode); ?>"/>
                </span>
            <? endif; ?>
        </div>

        <? // if you have a preview tab but want to move or remove the preview link
        // from this area of the record view, this can be split into
        // getPreviewData() (should stay here) and
        // getPreviewLink() (can go in your desired tab) ?>
        <?= $this->record($this->driver)->getPreviews() ?>
        <hr/>
        <?= $this->record($this->driver)->getToolbar() ?>
        <hr/>

        <? $isbns = $this->singleRecordInternationalStandardBookNumber($this->driver, true); ?>
        <? if (!empty($isbns)) : ?>
            <div id="other-editions" data-xid="<?=$isbns['0']?>">

            </div>
        <? endif;?>
        <?= $this->render('RecordDriver/SolrDefault/result-bibtip.phtml'); ?>
        <!--
        <? /*foreach ($this->related()->getList($this->driver) as $current): ?>
            <?= $this->related()->render($current) ?>
        <? endforeach; */?>
        -->
    </div>
</div>