<div class="row">
    <div class="col-sm-12">
        <h3 property="name">
            <? //$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?>
            <?= $this->escapeHtml($this->driver->getTitle()) ?>
        </h3>
    </div>
</div>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">

    <div class="col-sm-9">


        <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
        <? if ($summary): ?>
            <p><?=$this->truncate($summary, 300)?></p>

            <? if(strlen($summary) > 300): ?>
                <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
            <? endif; ?>
        <? endif; ?>

        <? if ($this->userlist()->getMode() !== 'disabled'): ?>
            <? /* Display the lists that this record is saved to */ ?>
            <div class="savedLists hidden alert alert-info" id="savedLists">
                <strong><?=$this->transEsc("Saved in")?>:</strong>
            </div>
        <? endif; ?>

        <?/* Display Main Details */?>
        <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">

            <!-- Titel -->
            <? $title = $this->singleRecordTitleStatement($this->driver); ?>
            <tr>
                <th><?= $this->transEsc('Title Statement') ?>:</th>
                <td>
                    <?= $title ?>
                </td>
            </tr>
            <!-- Unterreihe -->
            <? if ($this->driver->getMarcRecord()->getLeader()[19] == " ") : ?>

                <?$sectionOfWork = $this->singleRecordTitleStatementSectionOfWork($this->driver); ?>
                <? if ($sectionOfWork) : ?>
                    <tr>
                        <th><?= $this->transEsc('Title Statement Section of Work'); ?>:</th>
                        <td><?= $sectionOfWork ?></td>
                    </tr>
                <? endif; ?>

            <? endif; ?>

            <!-- Autor -->
            <? $authors = $this->singleRecordMainEntryPersonalName($this->driver); ?>
            <? if (!empty($authors)) : ?>
                <tr>
                    <th><?=$this->transEsc('Main Entry Personal Name')?>: </th>
                    <td property="author">
                        <?=  $authors ?><br />
                        <a href="<?//$this->record($this->driver)->getLink('author', $authors['main'])?>"><?//$this->escapeHtml($authors['main'])?></a>
                    </td>
                </tr>
            <? endif; ?>

            <!-- Beteiligt -->
            <? $addedEntryPersons = $this->singleRecordAddedEntryPersonalName($this->driver); ?>
            <? if ( !empty($addedEntryPersons)) : ?>
                <tr>
                    <th><?= $this->transEsc('Added Entry Personal Name'); ?>:</th>
                    <td property="creator"><?= $addedEntryPersons ?></td>
                </tr>
            <? endif; ?>

            <!-- Festschrift für -->
            <? $festschrift = $this->singleRecordFestschrift($this->driver); ?>
            <? if (!empty($festschrift)) : ?>
                <tr>
                    <th><?= $this->transEsc('Festschrift for'); ?></th>
                    <td><?= $festschrift ?></td>
                </tr>
            <? endif; ?>

            <!-- Interpret(en) -->
            <? $interpreter = $this->singleRecordInterpreter($this->driver); ?>
            <? if (!empty($interpreter)) : ?>
                <tr>
                    <th><?= $this->transEsc('Interpreter'); ?>:</th>
                    <td><?= $this->singleRecordInterpreter($this->driver) ?></td>
                </tr>
            <? endif; ?>

            <!-- Published in -->
            <? if ($this->driver->getMarcRecord()->getLeader()[19] == ' ') : ?>
                <? $marcJournal = $this->singleRecordMarcJournal($this->driver); ?>
                <? if ($marcJournal) : ?>
                    <tr>
                        <th><?= $this->transEsc('Marc Journal') ?>:</th>
                        <td><?= $marcJournal ?></td>
                    </tr>
                <? endif; ?>
            <? endif; ?>

            <!-- Veröffentlicht -->
            <? $publicationDistribution = $this->singleRecordPublicationDistribution($this->driver); ?>
            <? if (!empty($publicationDistribution)) : ?>
                <tr>
                    <th><?=$this->transEsc('Publication Distribution')?>:</th>
                    <td><?=$publicationDistribution?></td>
                </tr>
            <? endif; ?>

            <!-- Einheitssachtitel -->
            <? $uniformTitle = $this->singleRecordUniformTitle($this->driver); ?>
            <? if (!empty($uniformTitle)) : ?>
                <tr>
                    <th><?=$this->transEsc('Uniform Title')?>:</th>
                    <td><?=$uniformTitle?></td>
                </tr>
            <? endif; ?>

            <!-- Hochschulschrift -->
            <? $dissertationNote = $this->singleRecordDissertationNote($this->driver) ?>
            <? if (!empty($dissertationNote)) : ?>
                <tr>
                    <th><?=$this->transEsc('Dissertation Note')?>:</th>
                    <td><?= $dissertationNote ?></td>
                </tr>
            <? endif; ?>

            <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
            <? if (!empty($nextTitles)): ?>
                <tr>
                    <th><?=$this->transEsc('New Title')?>: </th>
                    <td>
                        <? foreach($nextTitles as $field): ?>
                            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
                        <? endforeach; ?>
                    </td>
                </tr>
            <? endif; ?>

            <? if (!empty($prevTitles)): ?>
                <tr>
                    <th><?=$this->transEsc('Previous Title')?>: </th>
                    <td>
                        <? foreach($prevTitles as $field): ?>
                            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
                        <? endforeach; ?>
                    </td>
                </tr>
            <? endif; ?>

            <!-- auch als -->
            <? $otherEditionEntry = $this->singleRecordOtherEditionEntry($this->driver); ?>
            <? if (!empty($otherEditionEntry)) : ?>
                <tr>
                    <th><?=$this->transEsc('Other Edition Entry')?>:</th>
                    <td><?=$otherEditionEntry?></td>
                </tr>
            <? endif; ?>

            <!-- Schlagworte -->
            <? $keywords = $this->singleRecordSubjectAddedKeywords($this->driver) ?>
            <? if (!empty($keywords)) : ?>
                <tr>
                    <th><?=$this->transEsc('Subject Added Keywords');?></th>
                    <td><?=$keywords?></td>
                </tr>
            <? endif; ?>

            <!-- auch als -->
            <? $additionalPhysical = $this->singleRecordAdditionalPhysicalFormAvailableNote($this->driver); ?>
            <? if (!empty($additionalPhysical)) : ?>
                <tr>
                    <th><?=$this->transEsc('Additional Physical Form Available Note')?></th>
                    <td><?=$additionalPhysical?></td>
                </tr>
            <? endif; ?>

            <!-- ISBN -->
            <? $isbn = $this->singleRecordInternationalStandardBookNumber($this->driver); ?>
            <? if (!empty($isbn)) : ?>
                <tr>
                    <th><?=$this->transEsc('ISBN')?>:</th>
                    <td><?=$isbn?></td>
                </tr>
            <? endif; ?>

            <!-- ISSN -->
            <? $issn = $this->singleRecordInternationalStandardSerialNumber($this->driver); ?>
            <? if (!empty($issn)) : ?>
                <tr>
                    <th><?=$this->transEsc('ISBN')?>:</th>
                    <td><?=$issn?></td>
                </tr>
            <? endif; ?>

            <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
                <tr>
                    <th><?=$this->transEsc('Format')?>: </th>
                    <td><?=$this->record($this->driver)->getFormatList()?></td>
                </tr>
            <? endif; ?>

            <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
                <tr>
                    <th><?=$this->transEsc('Language')?>: </th>
                    <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
                </tr>
            <? endif; ?>

            <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
                <tr>
                    <th><?=$this->transEsc('Edition')?>: </th>
                    <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
                </tr>
            <? endif; ?>

            <?/* Display series section if at least one series exists. */?>
            <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
                <tr>
                    <th><?=$this->transEsc('Series')?>: </th>
                    <td>
                        <? foreach ($series as $field): ?>
                            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
                            <? if (is_array($field)): ?>
                                <? if (!empty($field['name'])): ?>
                                    <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                                    <? if (!empty($field['number'])): ?>
                                        <?=$this->escapeHtml($field['number'])?>
                                    <? endif; ?>
                                    <br/>
                                <? endif; ?>
                            <? else: ?>
                                <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
                            <? endif; ?>
                        <? endforeach; ?>
                    </td>
                </tr>
            <? endif; ?>

            <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
                <tr>
                    <th><?=$this->transEsc('Subjects')?>: </th>
                    <td>
                        <? foreach ($subjects as $field): ?>
                            <div class="subjectLine" property="keywords">
                                <? $subject = ''; ?>
                                <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
                                <? $i = 0; foreach ($field as $subfield): ?>
                                    <?=($i++ == 0) ? '' : ' &gt; '?>
                                    <? $subject = trim($subject . ' ' . $subfield); ?>
                                    <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
                                <? endforeach; ?>
                            </div>
                        <? endforeach; ?>
                    </td>
                </tr>
            <? endif; ?>

            <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
                <tr>
                    <th><?=$this->transEsc('child_records')?>: </th>
                    <td>
                        <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
                    </td>
                </tr>
            <? endif; ?>

            <?
            //$openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails();
            ?>
            <? if (!empty($urls)): ?>
                <tr>
                    <th><?=$this->transEsc('Online Access')?>: </th>
                    <td>
                        <? foreach ($urls as $current): ?>
                            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
                        <? endforeach; ?>
                    </td>
                </tr>
            <? endif; ?>

            <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
            <? if(!empty($recordLinks)): ?>
                <tr>
                    <th><?=$this->transEsc('Related Items')?>:</th>
                    <td>
                        <? foreach ($recordLinks as $recordLink): ?>
                            <?=$this->transEsc($recordLink['title'])?>:
                            <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
                        <? endforeach; ?>
                        <? /* if we have record links, display relevant explanatory notes */
                        $related = $this->driver->getRelationshipNotes();
                        if (!empty($related)): ?>
                            <? foreach ($related as $field): ?>
                                <?=$this->escapeHtml($field)?><br/>
                            <? endforeach; ?>
                        <? endif; ?>
                    </td>
                </tr>
            <? endif; ?>

            <? if ($this->usertags()->getMode() !== 'disabled'): ?>
                <? $tagList = $this->driver->getTags(); ?>
                <tr>
                    <th><?=$this->transEsc('Tags')?>: </th>
                    <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
                        <div id="tagList">
                            <? if (count($tagList) > 0): ?>
                                <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
                            <? else: ?>
                                <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
                            <? endif; ?>
                        </div>
                    </td>
                </tr>
            <? endif; ?>
        </table>
        <?/* End Main Details */?>
    </div>
    <div class="col-sm-3">
        <div class="text-center">
            <? /* Display thumbnail if appropriate: */ ?>
            <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
            <? if ($mediumThumb): ?>
                <? if ($largeThumb): ?><a href="<?=$this->escapeHtmlAttr($largeThumb)?>"><? endif; ?>
                <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
                <? if ($largeThumb): ?></a><? endif; ?>
            <? else: ?>
                <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
            <? endif; ?>

            <? /* Display qrcode if appropriate: */ ?>
            <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
            <? if($QRCode): ?>
                <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
            <? endif; ?>
        </div>

        <? // if you have a preview tab but want to move or remove the preview link
        // from this area of the record view, this can be split into
        // getPreviewData() (should stay here) and
        // getPreviewLink() (can go in your desired tab) ?>
        <?=$this->record($this->driver)->getPreviews()?>
        <hr />
        <?=$this->record($this->driver)->getToolbar()?>
        <hr />
        <? foreach ($this->related()->getList($this->driver) as $current): ?>
            <?= $this->related()->render($current) ?>
        <? endforeach; ?>
    </div>
</div>
