<? $list = $this->params->getSortList();
if (!empty($list)): ?>
    <form class="form-horizontal" action="<?= $this->currentPath() ?>" method="get" name="sort">
        <div class="form-group">
            <?= $this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/')); ?>
            <label class="col-md-3 control-label" for="sort_options_1"><?= $this->transEsc('Sort') ?></label>
            <div class="col-md-9">
                <select id="sort_options_1" name="sort" class="jumpMenu form-control">
                    <? foreach ($list as $sortType => $sortData): ?>
                        <option
                            value="<?= $this->escapeHtmlAttr($sortType) ?>"<?= $sortData['selected'] ? ' selected="selected"' : '' ?>><?= $this->transEsc($sortData['desc']) ?></option>
                    <? endforeach; ?>
                </select>
            </div>
            <noscript><input type="submit" class="btn btn-default" value="<?= $this->transEsc("Set") ?>"/></noscript>
        </div>
    </form>
<? endif; ?>
