<? $list = $this->params->getSortList();
if (!empty($list)): ?>
    <form class="form-inline" action="<?= $this->currentPath() ?>" method="get" name="sort">
        <?= $this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/')); ?>
            <div class="form-group">
                <label class="control-label" for="sort_options_1" style="line-height: 38px;margin: 0;padding: 0;"><?= $this->transEsc('Sort') ?></label>
                <select id="sort_options_1" name="sort" class="jumpMenu form-control">
                    <? foreach ($list as $sortType => $sortData): ?>
                        <option
                                value="<?= $this->escapeHtmlAttr($sortType) ?>"<?= $sortData['selected'] ? ' selected="selected"' : '' ?>><?= $this->transEsc($sortData['desc']) ?></option>
                    <? endforeach; ?>
                </select>
            </div>
    </form>
<? endif; ?>
