<?
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    // Grab clean ISBN for convenience:
    $isbn = $this->driver->getCleanISBN();
?>
<table class="table table-striped" summary="<?=$this->transEsc('Description')?>">
    <!-- Bibliographischer Nachweis -->
    <? $refNote = $this->tabReferenceNote($this->driver); ?>
    <? if (!empty($refNote)): ?>
        <? $contentDisplayed = true; ?>
        <tr>
            <th><?=$this->transEsc('tab_description_reference_note')?>: </th>
            <td><?= $refNote ?></td>
        </tr>
    <? endif; ?>

    <? $relationShipEntry = $this->tabRelationshipEntry($this->driver); ?>
    <? if (!empty($relationShipEntry)): ?>
        <? $contentDisplayed = true; ?>
        <tr>
            <th><?= $this->transEsc('tab_description_relationship_entry'); ?></th>
            <td><?= $relationShipEntry ?></td>
        </tr>
    <? endif; ?>

    <? $tabNotes = $this->tabNotes($this->driver); ?>
    <? if (!empty($tabNotes)): ?>
        <? $contentDisplayed = true; ?>
        <tr>
            <th><?= $this->transEsc('tab_description_notes'); ?></th>
            <td><?= $tabNotes ?></td>
        </tr>
    <? endif; ?>

  <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <? endif; ?>
</table>
