<? if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<? $showCheckboxes = (isset($this->showCartControls) && $this->showCartControls)
    || (isset($this->showBulkOptions) && $this->showBulkOptions); ?>
<? $i = $this->indexStart; ?>

<div class="result-list">
    <? foreach ($this->results->getResults() as $current): ?>
        <? $recordNumber = $this->results->getStartRecord() + $i - $this->indexStart; ?>
        <div id="result-<?=$i++ ?>" class="row result-list-item<?= $current->supportsAjaxStatus() ? ' ajaxItem':''?>">
            <div class="col-xs-1">
                <?= $recordNumber ?>
            </div>
            <?= $this->record($current)->getSearchResult('list') ?>
        </div>
    <? endforeach; ?>
    <br />
    <div class="alert alert-info" role="alert"><?= $this->transEsc('custom_text_below_search_result');?></div>
</div>
