<?
// Set page title.
$this->headTitle($this->translate('Search Home'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

// Set default value if necessary:
if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
}

// Load search actions and settings (if any):
$options = $this->searchOptions($this->searchClassId);
$basicSearch = $options->getSearchAction();
$advSearch = $options->getAdvancedSearchAction();

$this->layout()->breadcrumbs = false;

$lookfor = is_array($this->lookfor) ? "" : $this->lookfor;
$ppnSearch = false;

$params = $this->params;

if (strpos($lookfor, "id:") !== false) {
    $ppnSearch = true;
    $ppn = str_replace("id:", "", $lookfor);
    $ppn = str_replace("HEB", "", $ppn);
}

// Set up search box:
$this->layout()->searchbox = $this->context($this)->renderInContext(
    'search/searchbox.phtml',
    [
        'lookfor' => $lookfor
    ]
);
?>

<div class="row">
    <div class="col-xs-12">
        <div class="jumbotron">
            <? if ($ppnSearch) : ?>
                <h2><?= $this->transEsc("not_in_stock")?></h2>

                <div class="lead">
                    <p><a title="<?= $this->transEsc('not_in_stocklink_in_new_window'); ?>" target="_blank" href="https://portal.hebis.de/jsp/customers/hebis/direktsuche/HDS.jsp?ppn=<?=$ppn?>">
                            <span class="hds-icon-link-ext"><!-- --></span>
                            <?= $this->transEsc("not_in_stock.interlibrary-loan-id", ["%1" => $ppn]) ?></a></p>
                    <p><?= $this->ppnLink()->getRecordLink($this->transEsc('not_in_stock.back_to_record'), $this->backlink) ?></p>
                </div>
            <? else : ?>
                <h2><?= $this->transEsc("not_in_stock")?></h2>
                <div class="lead">
                    <p>
                        <? if ($this->searchType === "advanced") : ?>
                        <?= $this->translate("not_in_stock.check_search", ["%1" => ""]) ?></p>
                        <? else : ?>
                            <?= $this->translate("not_in_stock.check_search", ["%1" => $this->lookfor]) ?></p>
                        <? endif; ?>
                       <?= $this->translate("not_in_stock.search_tips") ?>
                        <? if ($this->searchType === "advanced") : ?>

                            <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>">
                                <span class="hds-icon-edit"></span><?= $this->transEsc("not_in_stock.edit_advanced_search") ?>
                            </a>
                        <? endif; ?>
                    </p>
                </div>
            <? endif; ?>

        </div>
    </div>
</div>
