<?
$lookfor = $this->lookfor;
$searchIndex = $this->searchIndex;
if (!isset($this->searchTabs))  {
    $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $lookfor, $searchIndex);
} else {
    $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $lookfor, $searchIndex, $this->searchType, $this->hiddenFilters);
}
?>
<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
      <li<?=$tab['selected'] ? ' class="active"' : ''?>>
        <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
      </li>
    <? endforeach; ?>
  </ul>
<? endif; ?>