<?
// Set default value if necessary:
if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
}

// Load search actions and settings (if any):
$options = $this->searchOptions($this->searchClassId);
$handlers = $this->searchbox()->getHandlers(
    $this->searchClassId,
    isset($this->searchIndex) ? $this->searchIndex : null
);
$handlerCount = count($handlers);
$basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
$searchHome = $options->getSearchHomeAction();
$advSearch = $options->getAdvancedSearchAction();
//$lastSort = $options->getLastSort(); //not supported since VuFind 3.0.0
//$lastLimit = $options->getLastLimit(); //not supported since VuFind 3.0.0

if (!function_exists('getActiveHandler')) {
    function getActiveHandler($handlers) {
        $first = current($handlers);
        foreach ($handlers as $handler) {
            if ($handler['selected']) {
                return $handler;
            }
        }
        return $first;
    }
}

?>

    <form role="search" class="" method="get" action="<?= $this->url($basicSearch) ?>"
          name="searchForm" id="searchForm" autocomplete="off" style="">

        <!-- <div class="search-field-container"> --
            <div class="row">
                <div class="col-md-offset-2 col-md-8">
                    -->

        <!-- </div>
        </div> <!-- ./row -->

        <div class="col-xs-12">



            <!-- <div class="col-sm-2 hidden-md"> -->

            <!-- </div> -->
            <? $handler = getActiveHandler($handlers);?>
            <input type="hidden" name="type" id="search-option-type" value="<?= $this->escapeHtmlAttr($handler['value']) ?>" />
            <div class="input-group input-group-md" style="margin:1em 0 0 0;">

                <div class="input-group-addon hidden-sm hidden-md hidden-lg">
                    <a title="<?=$this->transEsc("Home"); ?>" href="<?=$this->config()->homeUrl()?>"><img class="img" src="<?=$this->basePath().$this->config()->themePath()?>/images/uni-logo-klein.svg" alt="<?= $this->config()->title()?>" /></a>
                </div>
            <!-- <? if ($this->searchbox()->autocompleteEnabled($this->searchClassId)): ?> autocomplete searcher:<?= $this->escapeHtmlAttr($this->searchClassId) ?><? endif ?> -->
                <input class="form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" id="searchForm_lookfor" type="text" name="lookfor" placeholder="<?= $this->translate('Search') ?>" value="<?= $this->escapeHtmlAttr($this->lookfor) ?>"/>
                <span class="input-group-btn">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                        <span id="selected-handler"><?=$this->transEsc($handler['label'])?></span>
                        <span class="caret"></span>
                    </button>
                    <ul id="select-search-handler" class="dropdown-menu dropdown-menu-right">
                        <? foreach ($handlers as $handler): ?>
                            <li>
                                <a href="#" data-value="<?= $this->escapeHtmlAttr($handler['value']) ?>" data-label="<?=$this->transEsc($handler['label'])?>"><?=$this->transEsc($handler['label'])?></a>
                            </li>
                        <? endforeach; ?>

                            <? foreach ($handlers as $handler): ?>
                                <!--
                                <div class="radio">


                                        <input type="radio" name="type" id="search-option-<?= $this->escapeHtmlAttr($handler['value']) ?>" value="<?= $this->escapeHtmlAttr($handler['value']) ?>"<?= $handler['selected'] ? ' checked="checked"' : '' ?>/>
                                        <?= $this->transEsc($handler['label']) ?>

                                        <!-- <a href="#"
                                       data-value="<?= $this->escapeHtmlAttr($handler['value']) ?>"><?= $handler['indent'] ? '-- ' : '' ?><?= $this->transEsc($handler['label']) ?></a>
                                    <!--
                                    value="<?= $this->escapeHtmlAttr($handler['value']) ?>"<?= $handler['selected'] ? ' selected="selected"' : '' ?>><?= $handler['indent'] ? '-- ' : '' ?><?= $this->transEsc($handler['label']) ?>
                                    -->

                                <!-- </div> -->
                            <? endforeach; ?>
                            <? if ($advSearch): ?>
                                <? if ($this->searchType == 'advanced'): ?>
                                    <? $hiddenFilterParams = $this->searchtabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?'); ?>
                                <li class="adv_search_links">
                                    <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Advanced")?></a>
                                </li>
                                <? else : ?>
                                    <li><a href="<?= $this->url($advSearch) ?>"><?= $this->transEsc("Advanced") ?> <span class="hds-icon-zoom-in"></span></a></li>
                                <? endif; ?>
                            <? endif; ?>
                    </ul>
                    <button type="submit" class="btn btn-primary">
                        <span class="hds-icon-search"></span>
                        <span class="sr-only"><?= $this->transEsc("Find") ?></span>
                    </button>
                </span>
            </div>
            <? $shards = $options->getShards();
            if ($options->showShardCheckboxes() && !empty($shards)): ?>
                <?
                $selectedShards = isset($this->selectedShards)
                    ? $this->selectedShards : $options->getDefaultSelectedShards();
                ?>
                <br/>
                <? foreach ($shards as $shard => $val): ?>
                    <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
                    <input type="checkbox" <?= $isSelected ? 'checked="checked" ' : '' ?>name="shard[]"
                           value='<?= $this->escapeHtmlAttr($shard) ?>'/> <?= $this->transEsc($shard) ?>
                <? endforeach; ?>
            <? endif; ?>
            <?
            $filterDetails = $this->searchbox()->getFilterDetails(
                isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
                isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
            );
            ?>
            <div class="row keep-filter">
                <div class="col-xs-12" style="padding-bottom: 0; color: #fff;">
                    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
                        <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
                        <div class="checkbox" style="margin-bottom: 0">
                            <label>
                                <input onChange="$('.applied-filter').click()" type="checkbox"<?= $defaultFilterState ?>
                                       id="searchFormKeepFilters"/>
                                <?= $this->transEsc("basic_search_keep_filters") ?>
                            </label>
                        </div>
                        <div class="hidden">
                            <? foreach ($filterDetails as $current): ?>
                                <input class="applied-filter" id="<?= $this->escapeHtmlAttr($current['id']) ?>"
                                       type="checkbox"<?= $defaultFilterState ?> name="filter[]"
                                       value="<?= $this->escapeHtmlAttr($current['value']) ?>"/>
                                <label
                                        for="<?= $this->escapeHtmlAttr($current['id']) ?>"><?= $this->escapeHtml($current['value']) ?></label>
                            <? endforeach; ?>
                            <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
                                <!-- this is a hidden element that flags whether or not default filters have been applied;
                                     it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
                                <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied"
                                       value="1"<?= $defaultFilterState ?> />
                            <? endif; ?>
                        </div>
                    <? else: ?>
                        <p><!-- --></p>
                    <? endif; ?>
                </div>
            </div>
            <?
            /* Show hidden field for active search class when in combined handler mode. */
            if ($this->searchbox()->combinedHandlersActive()) {
                echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
            }
            /* Load hidden limit preference from Session */
            if (!empty($lastLimit)) {
                echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
            }
            if (!empty($lastSort)) {
                echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
            }
            ?>
            <!-- <input type="hidden" name="type" value="AllFields"/> -->

        <? /*if ($advSearch): ?>
        <div class="col-xs-12 col-sm-3 col-md-2 link-adv-search">
            <a href="<?= $this->url($advSearch) ?>" class="btn btn-link"><span class="hds-icon-zoom-in"></span><?= $this->transEsc("Advanced") ?></a>
        </div>
        <? endif; */?>
        <? /*
        <? if ($handlerCount > 1): ?>
            <!--
            <select class="form-control" id="searchForm_type" name="type" data-native-menu="false">
                <? foreach ($handlers as $handler): ?>
                    <option
                        value="<?= $this->escapeHtmlAttr($handler['value']) ?>"<?= $handler['selected'] ? ' selected="selected"' : '' ?>><?= $handler['indent'] ? '-- ' : '' ?><?= $this->transEsc($handler['label']) ?></option>
                <? endforeach; ?>
            </select>
            -->
        <? elseif ($handlerCount == 1): ?>
            <input type="hidden" name="type" value="<?= $this->escapeHtmlAttr($handlers[0]['value']) ?>"/>
        <? endif; */ ?>

    </form>
    <script type="text/javascript">
        $("#searchForm_lookfor").focus()
    </script>
    </div>
<? //endif; ?>

