<?

$lookfor = $this->lookfor;
$searchIndex = $this->searchIndex;
//$this->searchIndex = $this->params->getSearchHandler();
//$this->searchType = $this->params->getSearchType();
//$this->searchId = $this->results->getSearchId();
//$this->searchClassId = $this->params->getSearchClassId();

if (!isset($this->searchTabs) && !empty($lookfor))  {
    $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $lookfor, $searchIndex);
} else {
    $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $lookfor, $searchIndex, $this->searchType, $this->hiddenFilters);
}
?>
<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
      <li id="<?=$tab["id"]?>"<?=$tab['selected'] ? ' class="active"' : ''?>>
        <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
        <? if ($tab["id"] === "EDS" && !$tab['selected'] && !empty($lookfor)) :
            $url = str_replace("/Search", "/ajax", $tab["url"]);

            $var = <<<EDSSCRIPT
    var url = "{$url}";
    $(document).ready(function() {
      $.getJSON(url, function (data) {
        $("#EDS > a").append(" <small id=\"eds-count\">("+data["data"]+")</small>");
      });
    });
EDSSCRIPT;
            $this->headScript()->appendScript($var);
        endif; ?>
      </li>
    <? endforeach; ?>
  </ul>
<? endif; ?>