<?
// Set default value if necessary:
if (!isset($this->searchClassId)) {
    if ($this->controllerName() === "EDS") {
        $this->searchClassId = 'EDS';
    } else {
        $this->searchClassId = 'Solr';
    }
}

// Load search actions and settings (if any):
$options = $this->searchOptions($this->searchClassId);
$handlers = $this->searchbox()->getHandlers(
    $this->searchClassId,
    isset($this->searchIndex) ? $this->searchIndex : null
);
$handlerCount = count($handlers);
$basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
$searchHome = $options->getSearchHomeAction();
$advSearch = $options->getAdvancedSearchAction();
$lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
$lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
$ignoreHiddenFilterMemory = isset($this->ignoreHiddenFilterMemory) && $this->ignoreHiddenFilterMemory;
$ignoreHiddenFiltersInRequest = isset($this->ignoreHiddenFiltersInRequest) && $this->ignoreHiddenFiltersInRequest;
$hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
    $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
    if (empty($hiddenFilters)) {
        $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId);
    }
}
$hiddenFilterParams = $this->searchtabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?');

function getActiveHandler($handlers) {
    $first = current($handlers);
    foreach ($handlers as $handler) {
        if ($handler['selected']) {
            return $handler;
        }
    }
    return $first;
}


?>

<form class="searchForm flip" method="get" action="<?=$this->url($basicSearch)?>" id="searchForm" name="searchForm" autocomplete="off">
    <div>
        <?= $this->context($this)->renderInContext('search/searchTabs', ['hiddenFilters' => $hiddenFilters]); ?>
        <? $handler = getActiveHandler($handlers);?>
        <div class="col-xs-12">
            <input type="hidden" name="type" id="search-option-type" value="<?= $this->escapeHtmlAttr($handler['value']) ?>" />
            <div class="input-group">
                <input class="searchForm_lookfor form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" type="text" name="lookfor" value="<?=($this->searchType != 'advanced') ? $this->escapeHtmlAttr($this->lookfor) : '' ?>"/>
                <div class="input-group-btn">
                    <? if ($handlerCount > 1): ?>
                        <!-- Button and dropdown menu -->
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span id="selected-handler"><?=$this->transEsc($handler['label'])?></span>
                            <span class="caret"></span>
                        </button>
                        <ul id="select-search-handler" class="dropdown-menu">
                            <? foreach ($handlers as $handler): ?>
                                <li id="<?= str_replace([":","|"], ["", "_"], $handler['value']) ?>" <?= $handler['selected'] ? 'class="active"' : '' ?>>
                                    <a href="#"
                                       data-value="<?= $this->escapeHtmlAttr($handler['value']) ?>"
                                       data-label="<?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?>">
                                        <?= $handler['selected'] ? '<span class="hds-icon-check"></span>' : '<span class="hds-icon-check-empty"></span>' ?>
                                        <?= $handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label']) ?>
                                    </a>
                                </li>
                            <? endforeach; ?>
                        </ul>
                    <? endif; ?>
                    <button type="submit" class="btn btn-primary" title="<?=$this->transEsc("Find")?>"><span class="hds-icon-search" aria-hidden="true"></span></button>
                </div>
            </div>
        </div>
        <div class="col-xs-12 indent-button-grp">
            <div class="pull-left">
            <? if ($this->searchType == 'advanced'): ?>
                <a class="btn btn-link" href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a>
            <? elseif ($advSearch): ?>
                <a href="<?=$this->url($advSearch) . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $hiddenFilterParams) ?>" class="btn btn-link" rel="nofollow"><?=$this->transEsc("Advanced")?></a>
            <? endif; ?>
            </div>

            <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
                <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
                <div class="pull-left" style="margin: 0; padding: 3px 0">
                    <label>
                        <input onChange="$('.applied-filter').click()" type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
                        <?=$this->transEsc("basic_search_keep_filters")?>
                    </label>
                </div>
                <div class="hidden">
                    <? foreach ($filterDetails as $current): ?>
                        <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
                        <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
                    <? endforeach; ?>
                    <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
                        <!-- this is a hidden element that flags whether or not default filters have been applied;
                             it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
                        <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
                    <? endif; ?>
                </div>
            <? endif; ?>


            <? if ($geoUrl = $this->geocoords()->getSearchUrl($options)) : ?>
                <a href="<?=$geoUrl ?>" class="btn btn-link"><?=$this->transEsc('Geographic Search')?></a>
            <? endif; ?>

            <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
                <?
                $selectedShards = isset($this->selectedShards)
                    ? $this->selectedShards : $options->getDefaultSelectedShards();
                ?>
                <br />
                <? foreach ($shards as $shard => $val): ?>
                    <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
                    <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
                <? endforeach; ?>
            <? endif; ?>
            <?
            $filterDetails = $this->searchbox()->getFilterDetails(
                isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
                isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
            );
            ?>

            <? foreach ($hiddenFilters as $key => $filter): ?>
                <? foreach ($filter as $value): ?>
                    <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
                <? endforeach; ?>
            <? endforeach; ?>
            <?
            /* Show hidden field for active search class when in combined handler mode. */
            if ($this->searchbox()->combinedHandlersActive()) {
                echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
            }
            /* Load hidden limit preference from Session */
            if (!empty($lastLimit)) {
                echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
            }
            if (!empty($lastSort)) {
                echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
            }
            ?>
        </div>

    </div>

</form>
<script type="text/javascript">$(".searchForm_lookfor:visible").focus()</script>

