<?

$lookfor = $this->lookfor;
$searchIndex = $this->searchIndex;
$searchMemory = $this->searchMemory();
//$this->searchIndex = $this->params->getSearchHandler();
//$this->searchType = $this->params->getSearchType();
//$this->searchId = $this->results->getSearchId();
//$this->searchClassId = $this->params->getSearchClassId();

if (!isset($this->searchTabs) && !empty($lookfor)
    && (isset($this->params) && is_object($this->params))) {
        $query = $this->params->getQuery();
        $type = ($query !== null && $query instanceof \VuFindSearch\Query\QueryGroup) ? 'advanced' : 'basic';
        $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $lookfor, $searchIndex, $type);

} else {
    $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $lookfor, $searchIndex, $this->searchType, $this->hiddenFilters);
}
?>
<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs indent-button-grp">
    <? foreach ($searchTabs as $tab): ?>
        <? //$img =($tab['id'] === "Solr") ? '<img style="width:26px;" src="'.$this->basePath().'/themes/hebisbs3/images/book_black.svg" />' : ''; ?>
      <li id="<?=$tab["id"]?>"<?=$tab['selected'] ? ' class="active"' : ''?>>
        <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
            <? //$img ?>
            <?=$this->transEsc($tab['label']); ?>
        </a>
        <? if ($tab["id"] === "EDS" && !$tab['selected'] && !empty($lookfor)) :
            $url = str_replace("/Search", "/ajax", $tab["url"]);

            $var = <<<EDSSCRIPT
    var url = "{$url}";
    $(document).ready(function() {
      $.getJSON(url, function (data) {
        $("#EDS > a").append(" <small id=\"eds-count\">("+data["data"]+")</small>");
      });
    });
EDSSCRIPT;
        $this->headScript()->appendScript($var); ?>

        <? elseif  ($tab['id'] === "Solr" && !$tab['selected']): ?>
            <? $url = str_replace("/Results", "/ajax", $tab["url"]);

                $var = <<<EDSSCRIPT
    var url = "{$url}";
        $(document).ready(function() {
        $.getJSON(url, function (data) {
        $("#Solr > a").append(" <small id=\"solr-count\">("+data["data"]+")</small>");
    });
});
EDSSCRIPT;
            $this->headScript()->appendScript($var); ?>
        <? endif; ?>

      </li>
    <? endforeach; ?>
  </ul>
<? endif; ?>