<div class="pub-date-vis-ajax">
<? $visFacets = $this->recommend->getVisFacets(); ?>
<? if ($visFacets): ?>

  <? /* load jQuery flot */ ?>
<?$this->headScript()->appendFile('vendor/flot/excanvas.min.js', null, array('conditional' => 'IE'));
  $this->headScript()->appendFile('vendor/flot/jquery.flot.min.js');
  $this->headScript()->appendFile('vendor/flot/jquery.flot.resize.min.js');
  $this->headScript()->appendFile('vendor/flot/jquery.flot.selection.min.js');
  $this->headScript()->appendFile('bootstrap-slider.min.js');
  $this->headScript()->appendFile('pubdate_vis.js'); ?>

  <? foreach ($visFacets as $facetField=>$facetRange): ?>
    <div class="authorbox">
      <div id="datevis<?=$this->escapeHtml($facetField)?>xWrapper" class="hidden">
        <strong><?=$this->transEsc($facetRange['label']) ?></strong>
        <? /* space the flot visualisation */ ?>
        <div id="datevis<?=$facetField ?>x" style="margin:0 10px;width:auto;height:80px;cursor:crosshair;"></div>
        <div id="clearButtonText" style="display: none"><?=$this->transEsc('Clear') ?></div>
      </div>
    </div>
  <? endforeach; ?>
  <div id="dateVisColorSettings"><!-- do not delete! used for passing CSS to Javascript --></div>
  <?
    $js = "loadVis('" . $this->recommend->getFacetFields() . "', '"
        . $this->recommend->getSearchParams() . "', '/', "
        . $this->recommend->getZooming() . ");\n"
        . "$(function() { $(\"#slider_publish_date\").slider({}); });";
    echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $js, 'SET');
  ?>

<? endif; ?>
    <input id="slider_publish_date" type="text" class="span2" value="" data-slider-min="10" data-slider-max="1000" data-slider-step="5" data-slider-value="[250,450]"/>
</div>