<!--
<? $results = $this->recommend->getResults(); ?>
<? if ($results->getResultTotal() > 0): ?>
    <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
    <?
    $html = '';
    $shown = 0;
    foreach ($checkboxFilters as $current) {
        $html .= '<label class="checkbox';
        if($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
            $html .= ' hidden';
        } else {
            $shown ++;
        }
        $html .= '"><input type="checkbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"
      onclick="document.location.href=\''.($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])).'\';" />'.$this->transEsc($current['desc']).'</label>';
    }
    ?>
    <div class="checkboxFilter<?if($shown == 0):?> hidden<? endif; ?>"><?=$html ?></div>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); if (!empty($filterList)): ?>
    <div class="list-group filters">
        <div class="list-group-item title"><?=$this->transEsc('Remove Filters')?></div>
        <? foreach ($filterList as $field => $filters): ?>
            <? foreach ($filters as $i => $filter): ?>
                <?
                $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
                if ($index !== false) {
                    unset($collapsedFacets[$index]); // Open if we have a match
                }
                if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
                    $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
                } else {
                    $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
                }
                if ($filter['displayText'] == '[* TO *]') {
                    $filter['displayText'] = $this->translate('filter_wildcard');
                }
                ?>
                <a class="list-group-item active" href="<?=$removeLink?>">
                    <span class="pull-right flip"><i class="fa fa-times"></i></span>
                    <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?>
                </a>
            <? endforeach; ?>
        <? endforeach; ?>
    </div>
<? endif; ?>
-->
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
    <? foreach ($sideFacetSet as $title => $cluster): ?>


        <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
        <? $facets_before_more = $this->recommend->getShowMoreSetting($title); ?>

        <? if (isset($rangeFacets[$title])): ?>
        <? if ($rangeFacets[$title]['type'] == 'date'): ?>
        <?
            $maxCount = $sideFacetSet["publish_date"]["list"][0]["count"];
            $minCount = $sideFacetSet["publish_date"]["list"][count($sideFacetSet["publish_date"]["list"])-1]["count"];
            usort($sideFacetSet["publish_date"]["list"], function ($a, $b) {
                return strcmp($a["value"], $b["value"]);
            });
            $yearMax = intval(substr(end($sideFacetSet["publish_date"]["list"])["value"], 0, 4));
            $yearMin = intval(substr(reset($sideFacetSet["publish_date"]["list"])["value"], 0, 4));
        ?>
        <div class="date-slider">
            <form name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter">
                <?=$results->getUrlQuery()->asHiddenFields(array('page' => "/./", 'filter' => "/^{$title}:.*/"))?>
                <input type="hidden" name="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtmlAttr($title)?>"/>
                <div class="row">
                    <? $extraInputAttribs = ($rangeFacets[$title]['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
                    <div class="col-sm-2">
                        <label for="<?=$this->escapeHtmlAttr($title)?>from">
                            <?=$this->transEsc('date_from')?>:
                        </label>
                        <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" value="<?=isset($rangeFacets[$title]['values'][0])?$this->escapeHtmlAttr($yearMin):''?>" <?=$extraInputAttribs?>/>
                    </div>
                    <div class="col-sm-8">

                        <ul class="timeline-list clearfix">
                            <?
                                $yearList = [];
                                array_walk($sideFacetSet["publish_date"]["list"], function($item) use (&$yearList) {
                                    $year = substr($item["value"], 0, 4);
                                    $yearList[$year] = $item;
                                });
                                for ($y = $yearMin; $y <= $yearMax; ++$y) {
                                    if (!array_key_exists($y, $yearList)) {
                                        $yearList[$y] = ["count" => 0, "value" => date(DateTime::ISO8601, strtotime("$y-01-01")), "displayText" => $y, "operator" => "AND", "isApplied" => false];
                                    }
                                }
                                ksort($yearList);
                                $maxHeight = 50;
                                foreach ($yearList as $year => $item) :
                                    $count = $item["count"];
                                    $height = ($count / $maxCount) * $maxHeight;
                                    $height = sprintf("%F", $height);
                                    ?>
                                    <li style="width:2px;" class="year-count-bar in-range">
                                        <a href="#" data-toggle="tooltip" data-placement="top" title="<?=$year?>: <?=$count?> <?=$this->transEsc("Entries")?>" data-year="<?=$year?>" data-count="<?=$count?>" style="height:<?=$height < 0.1 ? 1 : $height?>px;width:2px;"><!-- --></a>
                                    </li>
                                <? endforeach; ?>

                        </ul>
                        <div class="slider-container">

                            <input type="text" class="hidden" data-slider-handle="round" data-slider-min="<?=$yearMin?>" data-slider-max="<?=$yearMax?>" data-slider-step="1" data-slider-value="[<?=$yearMin?>,<?=$yearMax?>]" id="<?=$this->escapeHtmlAttr($title)?><?=$this->escapeHtml($rangeFacets[$title]['type'])?>Slider"/>
                        </div>

                    </div>
                    <div class="col-sm-2">
                        <label for="<?=$this->escapeHtmlAttr($title)?>to">
                            <?=$this->transEsc('date_to')?>:
                        </label>
                        <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>to" id="<?=$this->escapeHtmlAttr($title)?>to" value="<?=isset($rangeFacets[$title]['values'][1])?$this->escapeHtmlAttr($yearMax):''?>" <?=$extraInputAttribs?>/>
                    </div>
                </div>
                <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Set')?>"/>
            </form>

                <? if ($rangeFacets[$title]['type'] == 'date'): ?>
                <? $this->headScript()->appendFile('vendor/bootstrap-slider.js'); ?>
                <?
                $min = !empty($rangeFacets[$title]['values'][0]) ? min(substr($rangeFacets[$title]['values'][0],0,4), 1400) : 1400;
                $future = date('Y', time()+31536000);
                $max = !empty($rangeFacets[$title]['values'][1]) ? max($future, substr($rangeFacets[$title]['values'][1],0,4)) : $future;
                $low  = !empty($rangeFacets[$title]['values'][0]) ? substr($rangeFacets[$title]['values'][0],0,4) : $min;
                $high = !empty($rangeFacets[$title]['values'][1]) ? substr($rangeFacets[$title]['values'][1],0,4) : $max;
                $reversed = $this->layout()->rtl ? 'true' : 'false';
                $script = <<<JS
$(document).ready(function() {
  function roundUp(num) {
    return Math.ceil(num * 1000) / 1000;
  }
  $('[data-toggle="tooltip"]').tooltip();
  var fillTexts = function() {
  var v = {$this->escapeHtmlAttr($title)}dateSlider.getValue();
  $('#{$this->escapeHtmlAttr($title)}from').val(v[0]);
  $('#{$this->escapeHtmlAttr($title)}to').val(v[1]);
  };
  //console.log($('#{$this->escapeHtmlAttr($title)}dateSlider'));
  var {$this->escapeHtmlAttr($title)}dateSlider = $('#{$this->escapeHtmlAttr($title)}dateSlider')
    .slider({})
    .on('slide', fillTexts)
    .data('slider');
  var numItems = $(".timeline-list").children().length;
  var timelineWidth = $(".timeline-list").width();
  var itemWidth = (timelineWidth/numItems)-1;
  $(".timeline-list li").each(function(idx) {
      $(this).width(roundUp(itemWidth+1));
      $(this).children('a').width(roundUp(itemWidth));
  });
  $("#{$this->escapeHtmlAttr($title)}Filter").submit(function(e) {
      var from = $("#{$this->escapeHtmlAttr($title)}from").val();
      var to = $("#{$this->escapeHtmlAttr($title)}to").val();

      from = toIso(from);
      to = toIso(to);
      $("#{$this->escapeHtmlAttr($title)}from").val(from);
      $("#{$this->escapeHtmlAttr($title)}to").val(to);
      //$(this).submit();
  });
});
JS;
                ?>
                <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
                <? endif; ?>
                <? else: ?>
                <? if (in_array($title, $hierarchicalFacets)): ?>
                <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
                <? $this->headScript()->appendFile('facets.js'); ?>
                <? $sort = isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''; ?>
                <? if (!in_array($title, $collapsedFacets)): ?>
                <?
                $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
                ?>
                <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
                <? else: ?>
                <?
                $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($title)}').on('show.bs.collapse', function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
                ?>
                <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
                <? endif; ?>
                <li id="facet_<?=$this->escapeHtml($title)?>" class="jstree-facet"
                    data-facet="<?=$this->escapeHtmlAttr($title)?>"
                    data-path="<?=$this->currentPath()?>"
                    data-exclude="<?=$allowExclude?>"
                    data-operator="<?=$this->recommend->getFacetOperator($title)?>"
                    data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
                    data-sort="<?=isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''?>">
                </li>
                <noscript>
                    <? endif; ?>
                    <? foreach ($cluster['list'] as $i=>$thisFacet): ?>
              <?
                if(strlen($thisFacet['displayText']) == 0) {
                  $thisFacet['displayText'] = "-";
                }
              ?>
              <? $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
            <? if ($i == $facets_before_more): ?>
              <a id="more-narrowGroupHidden-<?=$this->escapeHtmlAttr($title)?>" class="list-group-item narrow-toggle" href="javascript:moreFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')"><?=$this->transEsc('more')?> ...</a>
            <? endif; ?>
            <? if ($thisFacet['isApplied']): ?>
              <a class="list-group-item active<? if ($i >= $facets_before_more): ?><?=$moreClass ?><?endif ?><? if ($thisFacet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']) ?>">
                <? if ($thisFacet['operator'] == 'OR'): ?>
                  <i class="fa fa-check-square-o"></i>
                <? else: ?>
                  <span class="pull-right flip"><i class="fa fa-check"></i></span>
                <? endif; ?>
                <?=$this->escapeHtml($thisFacet['displayText'])?>
              </a>
            <? else: ?>
              <? $addURL = $this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']); ?>
              <? if ($allowExclude): ?>
                <div class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
              <? else: ?>
                <a href="<?=$addURL ?>" class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
              <? endif; ?>
              <span class="badge">
                <?=$this->localizedNumber($thisFacet['count'])?>
                <? if ($allowExclude): ?>
                  <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times"></i></a>
                <? endif; ?>
              </span>
              <? if ($allowExclude): ?>
                <a href="<?=$addURL ?>">
              <? endif; ?>
              <? if($thisFacet['operator'] == 'OR'): ?>
                <i class="fa fa-square-o"></i>
              <? endif; ?>
              <?=$this->escapeHtml($thisFacet['displayText'])?>
              <? if ($allowExclude): ?>
                  </a>
                </div>
              <? else: ?>
                </a>
              <? endif; ?>
            <? endif; ?>
          <? endforeach; ?>
                    <? if ($i >= $facets_before_more): ?><a class="list-group-item narrow-toggle <?=$moreClass ?>" href="javascript:lessFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')"><?=$this->transEsc('less')?> ...</a><? endif; ?>
                    <? endif; ?>
                    <? if (in_array($title, $hierarchicalFacets)): ?>
                </noscript>
                <? endif; ?>
            </div>
    <? endif; ?>
    <? endforeach; ?>
<? endif; ?>


