<?php
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - Add'));
$this->headLink(['rel' => 'stylesheet', 'href' => $this->basePath() . "/themes/hebisbs3/js/wysiwyg-editor/summernote.css"]);
$this->headScript()->appendFile($this->basePath() . "/themes/hebisbs3/js/wysiwyg-editor/summernote.min.js");
$this->headScript()->appendFile($this->basePath() . '/themes/hebisbs3' . "/js/admin.js");
$activeLang = $this->layout()->userLang;
?>
<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h4><?= $this->transEsc('Add New Page') ?></h4>

        <ul class="nav nav-tabs">
            <? foreach ($this->langs as $code => $language) : ?>
                <li class="sp-form-<?= $code ?>" data-href="<?= $language ?>">
                    <a data-toggle="tab" href="#<?= $code ?>-form"
                       id="sp-lang-tab-<?= $code ?>"><?= $this->transEsc($language) ?></a>
                </li>
            <? endforeach; ?>
        </ul>
        <form id="new-post" method="post">
            <div class="tab-content">
                <? if ($this->error) : ?>
                    <div class="alert alert-danger">
                        <?= $this->translate("Fill out the form"); ?>
                    </div>
                <? endif; ?>
                <? foreach ($this->langs as $code => $language) : ?>
                    <div id="<?= $code ?>-form" class="sp-form-<?= $code ?> tab-pane fade">
                        <input type="hidden" class="form-control" name="sp-lang[]" value="<?= $code ?>">
                        <div class="form-group">
                            <input type="text" class="form-control sp-headline input-lg" name="sp-headline[]"
                                   placeholder="Headline"
                                   id="sp-headline" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control sp-nav-title input-sm" name="sp-nav-title[]"
                                   placeholder="<?= $this->translate('navigation Title') ?>"
                                   id="sp-headline" style="font-size: small" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <textarea type="text" class="wysiwig-text form-control" name="sp-content[]"></textarea>
                        </div>
                    </div>
                <? endforeach; ?>
            </div>
            <div class="form-group" id="sp-author">
                <div class="input-group">
                    <span class="input-group-addon" id="sp-<?= $this->transEsc('author'); ?>"><span
                                class="hds-icon-user-1"></span></span>
                    <input id="sp-author" type="text" placeholder="<?= $this->transEsc('author'); ?>" name="sp-author"
                           class="form-control">
                </div>
            </div>
            <div class="form-group">
                <button tabindex="0" class="btn btn-default" data-ignore="true"
                        data-toggle="popover" data-placement="auto right"
                        data-trigger="focus" data-title="Please Note"
                        data-content="<?= $this->transEsc('input fields of other languages might be empty!') ?>"
                        id="sp-save"><?= $this->transEsc('Save'); ?>
                </button>
            </div>
            <!--div style="border: dashed">
                <span class="label label-warning">input fields of other languages might be empty! <a>continue anyway</a></span>
            </div-->
        </form>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
