<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - Home'));
$this->headScript()->appendFile($this->basePath() . '/themes/hebisbs3' . "/js/admin.js");
$lang = $this->layout()->userLang;
?>

<!--Modal-->
<div class="modal fade" id="admin-delete-confirmation" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" id="cross">&times;</button>
                <div class="pull-left col-md-2" style="font-size:300%">
                    <span class="hds-icon-trash-empty"><!-- --></span>
                </div>
                <p id="admin-delete-question"><?= $this->translate('Are you sure?') ?><i></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"
                        id="delete-confirmation-button"><?= $this->translate('Delete') ?></button>
            </div>
        </div>
    </div>
</div>
<!--End of Modal-->

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h3><span class="hds-icon-journal"></span>&nbsp;Static<b>Pages</b></h3>
        <hr>
        <? $oldpid = -1; ?>
        <ul id="admin-list">
            <li>
                <div class="sp">
                    <span class="hds-icon-plus-circled"></span>
                    <a href="<?= $this->url('pageadmin/add') ?>"><i><?= $this->transEsc('Add New Page') ?></a>
                </div>
            </li>
            <? foreach ($this->rows as $row) : ?>
                <? if ($row->language !== $lang) {
                    continue;
                } ?>
                <? $pid = $row->pid;
                $headline = $row->headline; ?>
                <? if ($pid !== $oldpid) : ?>
                    <li>
                        <div class="sp">
                            <span class="admin-delete-button hds-icon-trash"
                                  data-href="<?= $headline ?>"
                                  href="<?= $this->url('pageadmin/json', ['method' => 'delete', 'pid' => $pid]) ?>"
                                  id="<?= $pid ?>">
                            </span>
                            <span class="sp-page-visibility <?= ($row->visible == 1) ? "hds-icon-eye green" : "hds-icon-eye-off red" ?>"
                                  href="<?= $this->url('pageadmin/json', ['method' => 'visible', 'pid' => $pid]) ?>">
                            </span>
                            <a class="hds-icon-edit" href="<?= $this->url('pageadmin/edit', ['pid' => $pid]) ?>"></a>
                            <a href="<?= $this->url('pageadmin/preview', ['pid' => $pid]) ?>"><?= $headline ?></a>
                        </div>
                    </li>
                <? endif; ?>
                <? $oldpid = $pid; ?>
            <? endforeach; ?>
        </ul>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
