<?php

$activeLang = $this->layout()->userLang;
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - Edit'));
$this->headLink(['rel' => 'stylesheet', 'href' => $this->basePath() . "/themes/hebisbs3/js/wysiwyg-editor/summernote.css"]);
$this->headScript()
    ->appendFile($this->basePath() . '/themes/hebisbs3/js/admin.js')
    ->appendFile($this->basePath() . '/themes/hebisbs3/js/wysiwyg-editor/summernote.min.js')
    ->appendFile($this->basePath() . '/themes/hebisbs3/js/wysiwyg-editor/lang/summernote-de-DE.js')
    ->appendScript('$(document).ready(function() {$(".wysiwig-editor").summernote({height : 200, lang : "de-DE"});});', $type = 'text/javascript');
?>
<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h4><?= $this->transEsc('Edit Page') ?></h4>

        <ul class="nav nav-tabs">
            <? foreach ($this->langs as $code => $language) : ?>
                <li class="sp-form">
                    <a data-toggle="tab"
                       lang="<?= $code ?>"
                       href="#admin-<?= $code ?>-form"
                       id="admin-lang-tab-<?= $code ?>"><?= $this->transEsc($language) ?></a>
                </li>
            <? endforeach; ?>
        </ul>
        <!-- Tab Contents -->

        <form id="new-post" method="post">
            <div class="tab-content">
                <? foreach ($this->langs as $code => $language) : ?>
                    <div class="tab-pane fade" id="admin-<?= $code ?>-form">
                        <input type="hidden" class="form-control" name="sp-lang[]" value="<?= $code ?>">

                        <div class="form-group">
                            <input type="text" class="form-control sp-headline input-lg" name="sp-headline[]"
                                   placeholder="Headline"
                                   value="<?= $this->rows[$code]['headline'] ?>"
                                   id="sp-headline" autocomplete="off">
                        </div>

                        <div class="form-group">
                            <input type="text" class="form-control sp-nav-title input-sm" name="sp-nav-title[]"
                                   placeholder="<?= $this->translate('navigation Title') ?>"
                                   value="<?= $this->rows[$code]['nav_title'] ?>"
                                   id="sp-headline" style="font-size: small" autocomplete="off">
                        </div>

                        <div class="form-group">
                            <textarea class="form-control wysiwig-editor"
                                      name="sp-content[]"><?= $this->rows[$code]['content'] ?></textarea>
                        </div>
                    </div>
                <? endforeach; ?>
            </div>
            <div class="form-group" id="sp-author">
                <div class="input-group">
                    <span class="input-group-addon hds-icon-user-1" id="admin-author"></span>
                    <input class="form-control"
                           type="text"
                           placeholder="<?= $this->transEsc('author'); ?>"
                           value="<?= $this->rows['en']['author'] ?>"
                           name="sp-author"
                           id="sp-author">
                </div>
            </div>
            <div class="form-group">
                <button tabindex="0" class="btn btn-default"
                        data-toggle="popover" data-placement="auto right"
                        id="sp-save"><?= $this->transEsc('Save'); ?>
                </button>
            </div>
        </form>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
