<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - View'));
?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <?= $this->render("page/sp-body.phtml") ?>
        <a class="btn btn-default"
           href="<?= $this->url('pageadmin') ?>"
           data-toggle="tooltip"
           title="<?= $this->transEsc('back_to_overview') ?>"><span
                    class="hds-icon-angle-left"></span><?= $this->transEsc('Back') ?></a>
        <a class="btn btn-default"
           href="#toplink"
           data-toggle="tooltip"
           title="<?= $this->transEsc('back_to_top') ?>"><span
                    class="hds-icon-angle-double-up"></span><?= $this->transEsc('Top') ?></a>
    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
