<?
$this->headTitle('VuFind Administration - ' . $this->translate('Static Pages - View'));
?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <?= $this->render("page/sp-body.phtml") ?>
        <a class="btn btn-default"
           href="<?= $this->url('pageadmin') ?>"
           data-toggle="tooltip"
           title="<?= $this->transEsc('Back to overview') ?>">←</a>
    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
