<? $account = $this->auth()->getManager(); ?>
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="hds-icon-menu"></span>
    </button>
    <!--
    <a role="logo" class="navbar-brand" href="<?= $this->url('home') ?>">VuFind</a>
    -->
</div>

<? if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
        <ul role="navigation" class="nav navbar-nav navbar-right">
            <? if ($this->feedback()->tabEnabled()): ?>
                <li>
                    <a id="feedbackLink" class="modal-link" href="<?= $this->url('feedback-home') ?>"><i
                            class="fa fa-envelope"></i> <?= $this->transEsc("Feedback") ?></a>
                </li>
            <? endif; ?>
            <? $cart = $this->cart();
            if ($cart->isActive()): ?>
                <li id="cartSummary">
                    <a id="cartItems" class="modal-link" title="<?= $this->transEsc('View Book Bag') ?>"
                       href="<?= $this->url('cart-home') ?>"><i class="fa fa-suitcase"></i>
                        <strong><?= count($cart->getItems()) ?></strong> <?= $this->transEsc('items') ?><?= $cart->isFull() ? ' (' . $this->transEsc('bookbag_full') . ')' : '' ?>
                    </a>
                </li>
            <? endif; ?>
            <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
                <li class="logoutOptions<? if (!$account->isLoggedIn()): ?> hidden<? endif ?>">
                    <a href="<?= $this->url('myresearch-home', array(), array('query' => array('redirect' => 0))) ?>"
                       class="modal-link" title="<?= $this->transEsc("Your Account") ?>"><span
                            class="hds-icon-home"></span> <?= $this->transEsc("Your Account") ?></a>
                </li>
                <li class="logoutOptions<? if (!$account->isLoggedIn()): ?> hidden<? endif ?>">
                    <a href="<?= $this->url('myresearch-logout') ?>" class="modal-link"
                       title="<?= $this->transEsc("Log Out") ?>"><span
                            class="hds-icon-logout"></span> <?= $this->transEsc("Log Out") ?></a>
                </li>
                <li id="loginOptions"<? if ($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
                    <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                        <a href="<?= $this->escapeHtmlAttr($sessionInitiator) ?>"><i
                                class="fa fa-sign-in"></i> <?= $this->transEsc("Institutional Login") ?></a>
                    <? else: ?>
                        <a href="<?= $this->url('myresearch-userlogin') ?>" class="modal-link"
                           title="<?= $this->transEsc("Login") ?>"><i
                                class="hds-icon-login"></i> <?= $this->transEsc("Login") ?></a>
                    <? endif; ?>
                </li>
            <? endif; ?>

            <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
                <li class="dropdown">
                    <form method="post" name="themeForm" action="" id="themeForm">
                        <input type="hidden" name="ui"/>
                    </form>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc("Theme") ?> <b
                            class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <? foreach ($this->layout()->themeOptions as $current): ?>
                            <li<?= $current['selected'] ? ' class="active"' : '' ?>><a href="#"
                                                                                       onClick="document.themeForm.ui.value='<?= $this->escapeHtmlAttr($current['name']) ?>';document.themeForm.submit()"><?= $this->transEsc($current['desc']) ?></a>
                            </li>
                        <? endforeach; ?>
                    </ul>
                </li>
            <? endif; ?>

            <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
                <li class="language dropdown">
                    <form method="post" name="langForm" id="langForm">
                        <input type="hidden" name="mylang" id="mylang"/>
                    </form>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                            <li <?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" class="lang-switch" data-langcode="<?=$langCode?>" ><?=$this->displayLanguageOption($langName)?></a></li>
                        <? endforeach; ?>
                    </ul>

                </li>
            <? endif; ?>
        </ul>
    </div>
<? endif; ?>
