<div class="col-sm-10">
    <!-- logo -->
    <div class="uni-logo pull-left hidden-xs">
        <a href="http://hds.hebis.de/">
            <img class="img-responsive" style="width:100%;" src="<?= $this->basePath()."/themes/hebisbs3/images/HeBIS-Logo.svg"?>" alt="HeBIS HDS">
        </a>
        <!--
        <span class="departmentName"><a href="<?=$this->basePath()?>">HDS <small>HeBIS Discovery System</small></a></span>
        -->
    </div>
    <!--
    <div class="department clearfix">

    </div>
    -->
</div>