<div class="col-sm-10">
    <!-- logo -->
    <div class="uni-logo pull-left hidden-xs">
        <a href="http://hds.hebis.de/">
            <img src="<?= $this->basePath()."/themes/hebisbs3/images/HeBIS-Logo.svg"?>" height="80" alt="HeBIS HDS">
        </a>
    </div>
    <div class="department clearfix">
        <span class="departmentName"><a href="<?=$this->basePath()?>">HDS <small>HeBIS Discovery System</small></a></span>
    </div>
</div>