<?php
$this->headTitle('VuFind Administration - ' . $this->translate('Broadcasts - Add'));
$this->headScript()->appendFile($this->basePath() . '/themes/hebisbs3/js/admin.js');
$activeLang = $this->layout()->userLang;
?>
<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">

        <form id="new-post" method="post">

            <ul class="nav nav-tabs">
                <? foreach ($this->langs as $code => $language) : ?>
                    <li class="bc-form">
                        <a data-toggle="tab"
                           lang="<?= $code ?>"
                           href="#<?= $code ?>-form"
                           id="bc-lang-tab-<?= $code ?>"><?= $this->transEsc($language) ?></a>
                    </li>
                <? endforeach; ?>
            </ul>

            <div class="tab-content">
                <? foreach ($this->langs as $code => $language) : ?>
                    <div id="<?= $code ?>-form" lang="<?= $code ?>" class="bc-form-<?= $code ?> tab-pane fade">

                        <div class="bc-alert alert alert-warning"></div>

                        <input type="hidden" class="form-control" name="bc-lang[]" value="<?= $code ?>">

                        <div class="form-group">
                            <input type="text" class="form-control bc-message input-md" name="bc-message[]"
                                   placeholder="<?= $this->translate('Broadcast Message') ?>"
                                   style="font-size: small" autocomplete="off" id="bc-message-<?= $code ?>">
                        </div>

                    </div>
                <? endforeach; ?>
            </div>

            <div class="form-group">
                <div class="btn-group btn-group-xs bc-types" data-toggle="buttons">
                    <label class="btn btn-success btn-xs">
                        <input type="radio" name="bc-type" value="success" autocomplete="off"
                               checked> <?= $this->transEsc('bc-success') ?>
                    </label>
                    <label class="btn btn-info btn-xs">
                        <input type="radio" name="bc-type" value="info"
                               autocomplete="off"> <?= $this->transEsc('bc-info') ?>
                    </label>
                    <label class="btn btn-warning btn-xs active">
                        <input type="radio" name="bc-type" value="warning"
                               autocomplete="off"> <?= $this->transEsc('bc-warning') ?>
                    </label>
                    <label class="btn btn-danger btn-xs">
                        <input type="radio" name="bc-type" value="danger"
                               autocomplete="off"><?= $this->transEsc('bc-danger') ?>
                    </label>
                </div>
            </div>

            <div class="form-group">
                <button tabindex="0" class="btn btn-default" data-ignore="true"
                        data-toggle="popover" data-placement="auto right"
                        data-trigger="focus" data-title="Please Note"
                        data-content="<?= $this->transEsc('input fields of other languages might be empty!') ?>"
                        id="bc-save"><?= $this->transEsc('Save'); ?>
                </button>
            </div>
        </form>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
