<?php
$this->headTitle('VuFind Administration - ' . $this->translate('Broadcasts - Add'));
$this->headLink(['rel' => 'stylesheet', 'href' => $this->basePath() . "/themes/hebisbs3/js/datepicker/css/bootstrap-datepicker3.css"]);
$this->headScript()
    ->appendFile($this->basePath() . '/themes/hebisbs3/js/admin.js')
    ->appendFile($this->basePath() . '/themes/hebisbs3/js/datepicker/js/bootstrap-datepicker.js');

$activeLang = $this->layout()->userLang;
?>
<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">



            <!-- Language Tabs -->

            <ul class="nav nav-tabs">
                <? foreach ($this->langs as $code => $language) : ?>
                    <li class="bc-form">
                        <a data-toggle="tab"
                           lang="<?= $code ?>"
                           href="#<?= $code ?>-form"
                           id="bc-lang-tab-<?= $code ?>"><?= $this->transEsc($language) ?></a>
                    </li>
                <? endforeach; ?>
            </ul>

            <!-- Tab Contents -->
            <form id="new-bc" class="form-horizontal" method="post">
            <div class="tab-content">

                <? foreach ($this->langs as $code => $language) : ?>

                    <div lang="<?= $code ?>" class="bc-form-<?= $code ?> tab-pane fade" id="<?= $code ?>-form">
                        <div class="form-group">
                            <div class="col-sm-offset-2">
                                <div class="bc-alert alert alert-warning" style="margin: 0 1em;">&nbsp;</div>
                            </div>
                        </div>


                        <input type="hidden" class="form-control" name="bc-lang[]" value="<?= $code ?>">

                        <div class="form-group">
                            <label for="bc-expireDate" class="col-sm-2 control-label"><?= $this->transEsc('message') ?></label>
                            <div class="col-sm-10">
                                <div class="input-group">
                                <input type="text" class="form-control bc-message input-md" name="bc-message[]"
                                       placeholder="<?= $this->translate('Broadcast Message') ?>"
                                       autocomplete="off" id="bc-message-<?= $code ?>">
                                    <div class="input-group-btn bc-types" data-toggle="buttons">
                                        <label class="btn btn-success">
                                            <input class="form-control" type="radio" name="bc-type" value="success"
                                                   autocomplete="off">&nbsp;
                                        </label>
                                        <label class="btn btn-info">
                                            <input class="form-control" type="radio" name="bc-type" value="info"
                                                   autocomplete="off">&nbsp;
                                        </label>
                                        <label class="btn btn-warning active">
                                            <input class="form-control" type="radio" name="bc-type" value="warning"
                                                   autocomplete="off" checked>&nbsp;
                                        </label>
                                        <label class="btn btn-danger">
                                            <input class="form-control" type="radio" name="bc-type" value="danger"
                                                   autocomplete="off">&nbsp;
                                        </label>
                                    </div>
                                </div>
                                <!--
                                <div class="input-group-btn bc-types" data-toggle="buttons">
                                    <label class="btn btn-success">
                                        <input class="form-control" type="radio" name="bc-type" value="success"
                                               autocomplete="off">&nbsp;
                                    </label>
                                    <label class="btn btn-info">
                                        <input class="form-control" type="radio" name="bc-type" value="info"
                                               autocomplete="off">&nbsp;
                                    </label>
                                    <label class="btn btn-warning active">
                                        <input class="form-control" type="radio" name="bc-type" value="warning"
                                               autocomplete="off" checked>&nbsp;
                                    </label>
                                    <label class="btn btn-danger">
                                        <input class="form-control" type="radio" name="bc-type" value="danger"
                                               autocomplete="off">&nbsp;
                                    </label>
                                </div>
                                -->
                            </div>
                        </div>

                    </div>
                <? endforeach; ?>
            </div>

            <div class="form-group">
                <label for="bc-expireDate" class="col-sm-2 control-label"><?= $this->transEsc('expire date') ?></label>
                <div class="col-sm-10">
                    <div class="input-group date" data-provide="datepicker">
                        <input type="text" class="form-control" id="bc-expireDate" name="bc-expireDate">
                        <div class="input-group-addon hds-icon-calendar-empty"></div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button tabindex="0" class="btn btn-default" data-ignore="true"
                            data-toggle="popover" data-placement="auto right"
                            id="bc-save"><?= $this->transEsc('Save'); ?>
                    </button>
                </div>
            </div>
            </form>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
