<?php
$this->headTitle('VuFind Administration - ' . $this->translate('Broadcasts - Edit'));
$this->headLink(['rel' => 'stylesheet', 'href' => $this->basePath() . "/themes/hebisbs3/js/datepicker/css/bootstrap-datepicker3.css"]);
$this->headScript()
    ->appendFile($this->basePath() . '/themes/hebisbs3/js/admin.js')
    ->appendFile($this->basePath() . '/themes/hebisbs3/js/datepicker/js/bootstrap-datepicker.js');

$activeLang = $this->layout()->userLang;
?>
<div class="row">

    <div class="<?= $this->layoutClass('mainbody') ?>">

        <form id="new-bc" method="post">

            <!-- Language Tabs -->

            <ul class="nav nav-tabs">
                <? foreach ($this->langs as $code => $language) : ?>
                    <li class="bc-form">
                        <a data-toggle="tab"
                           lang="<?= $code ?>"
                           href="#<?= $code ?>-form"
                           id="bc-lang-tab-<?= $code ?>"><?= $this->transEsc($language) ?></a>
                    </li>
                <? endforeach; ?>
            </ul>

            <!-- Tab Contents -->

            <div class="tab-content">
                <? foreach ($this->langs as $code => $language) : ?>
                    <div lang="<?= $code ?>" class="bc-form-<?= $code ?> tab-pane fade" id="<?= $code ?>-form">
                        <? foreach ($this->rowSet as $row) : ?>
                            <? if ($row['language'] === $code) : ?>
                                <div class="bc-alert alert alert-<?= $row['type'] ?>">&nbsp;</div>

                                <input type="hidden" class="form-control" name="bc-lang[]" value="<?= $code ?>">
                                <div class="input-group form-group">
                                    <input type="text" class="form-control bc-message input-md" name="bc-message[]"
                                           value="<?= $row['message'] ?>"
                                           autocomplete="off" id="bc-message-<?= $code ?>">

                                    <div class="input-group-btn bc-types" data-toggle="buttons">
                                        <label class="btn btn-success">
                                            <input class="form-control" type="radio" name="bc-type" value="success"
                                                   autocomplete="off">&nbsp;
                                        </label>
                                        <label class="btn btn-info">
                                            <input class="form-control" type="radio" name="bc-type" value="info"
                                                   autocomplete="off">&nbsp;
                                        </label>
                                        <label class="btn btn-warning">
                                            <input class="form-control" type="radio" name="bc-type" value="warning"
                                                   autocomplete="off">&nbsp;
                                        </label>
                                        <label class="btn btn-danger">
                                            <input class="form-control" type="radio" name="bc-type" value="danger"
                                                   autocomplete="off" checked>&nbsp;
                                        </label>
                                    </div>
                                </div>

                            <? endif; ?>
                        <? endforeach; ?>
                    </div>
                <? endforeach; ?>
            </div>

            <div class="form-group">
                <div class="input-group date" data-provide="datepicker">
                    <input type="text" class="form-control" name="bc-expireDate" value="<?= $this->expireDate ?>">
                    <div class="input-group-addon hds-icon-calendar-empty"></div>
                </div>
            </div>

            <div class="form-group">
                <button tabindex="0" class="btn btn-default" data-ignore="true"
                        data-toggle="popover" data-placement="auto right"
                        id="bc-save"><?= $this->transEsc('Save'); ?>
                </button>
            </div>
        </form>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
