<?
$this->headTitle('VuFind Administration - ' . 'Broadcast Admin');
$this->headScript()->appendFile($this->basePath() . '/themes/hebisbs3' . '/js/admin.js');
$this->headScript()->appendFile($this->basePath() . '/themes/hebisbs3' . '/js/bootstrap2-toggle.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/themes/hebisbs3' . '/css/bootstrap2-toggle.min.css', 'all');
$lang = $this->layout()->userLang;
?>

<!--Modal-->
<div class="modal fade" id="bc-delete-confirmation" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" id="cross">&times;</button>
                <div class="pull-left col-md-2" style="font-size:300%">
                    <span class="hds-icon-trash-empty"><!-- --></span>
                </div>
                <p id="bc-delete-question"><?= $this->translate('Are you sure?') ?><i></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"
                        id="delete-confirmation-button"><?= $this->translate('Delete') ?></button>
            </div>
        </div>
    </div>
</div>
<!--End of Modal-->
<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h3><span class="hds-icon-bullseye"></span><b>Broadcasts</b></h3>
        <hr>
        <div class="post">
            <div class="col-xs-12 col-sm-10">
                <span class="hds-icon-plus-circled"></span>
                <a href="<?= $this->url('broadcastadmin', ['action' => 'add']) ?>"><i><?= $this->transEsc('Add New Broadcast') ?></i></a>
            </div>
            <div class="col-xs-12 col-sm-2">

            </div>
        </div>
        <?
        $visibilitySymbols = array(
            'visible' => '<span class="hds-icon-eye green"></span>',
            'unvisible' => '<span class="hds-icon-eye-off red"></span>',
        ); ?>
        <? $oldbcid = -1; ?>
        <? foreach ($this->rows as $row) : ?>
            <? if ($row->language !== $lang) {
                continue;
            } ?>
            <? $bcid = $row->bcid; ?>
            <? if ($bcid !== $oldbcid) : ?>
                <div class="broadcast" id="<?= $bcid ?>" data-href="<?= $row->message ?>">
                    <div class="col-xs-12 col-sm-10">
                        <input class="bc-toggle" type="checkbox" <?= ($row->show == 1) ? 'checked' : '' ?>
                               data-toggle="toggle" data-size="mini">
                        <a href="<?= $this->url('broadcastadmin', ['action' => 'preview', 'bcid' => $bcid]) ?>"><?= $row->message ?></a>
                    </div>
                    <div class="col-xs-12 col-sm-2">
                        <a href="<?= $this->url('broadcastadmin', ['action' => 'edit', 'bcid' => $bcid]) ?>">
                            <span class="hds-icon-edit"><!--></span></a>
                        <span class="bc-delete-button" id="<?= $bcid ?>"
                              href="<!--?= $this->url('broadcastadmin/json', ['method' => 'delete', 'bcid' => $bcid]) ?-->">
                        <span class="hds-icon-trash"><!--></span>
                    </span>
                    </div>
                </div>
            <? endif; ?>
            <? $oldbcid = $bcid; ?>
        <? endforeach; ?>


    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>
