<?
// Set page title.
$this->headTitle($this->translate('VuFind Administration - Logs'));
// Scroll to bottom of text field
$this->headScript()->appendScript('
    $(document).ready(function() {
        var textarea = document.getElementById("log");
        textarea.scrollTop = textarea.scrollHeight;
    });
    ');
?>

<div class="row">
    <div class="<?= $this->layoutClass('mainbody') ?>">
        <h3><?= $this->transEsc('Logs') ?></h3>

        <textarea class="log-box"
                  rows="19" title="recentlog"><?= $this->logContent; ?></textarea>

    </div>
    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?= $this->render("admin/menu.phtml") ?>
    </div>
</div>