<?= $this->doctype('HTML5') ?>
<? $nav = $this->staticPageNavigation();

?>
<html lang="<?= $this->layout()->userLang ?>">
<head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <style media="screen" type="text/css">
        @font-face {
            font-family: 'vufind-hds';
            src: url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.eot?45523202');
            src: url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.eot?45523202#iefix') format('embedded-opentype'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.woff2?45523202') format('woff2'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.woff?45523202') format('woff'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.ttf?45523202') format('truetype'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.svg?45523202#vufind-hds') format('svg');
            font-weight: normal;
            font-style: normal;
        }
    </style>
        <?
          // Set up OpenSearch link:
          $this->headLink(
            array(
              'href' => $this->url('search-opensearch') . '?method=describe',
              'type' => 'application/opensearchdescription+xml',
              'title' => $this->transEsc('Library Catalog Search'),
              'rel' => 'search'
            )
          );
        ?>
        <!-- RTL styling -->
        <? if ($this->layout()->rtl) {
          $this->headLink()->appendStylesheet('vendor/bootstrap-rtl.min.css');
        } ?>
        <?=$this->headLink()?>
        <?=$this->headStyle()?>
        <?
          if (!isset($this->renderingError)) {
            // Add translation strings
            $this->jsTranslations()->addStrings(
              array(
                'add_tag_success' => 'add_tag_success',
                'bulk_email_success' => 'bulk_email_success',
                'bulk_noitems_advice' => 'bulk_noitems_advice',
                'bulk_save_success' => 'bulk_save_success',
                'close' => 'close',
                'collection_empty' => 'collection_empty',
                'error_occurred' => 'An error has occurred',
                'go_to_list' => 'go_to_list',
                'libphonenumber_invalid' => 'libphonenumber_invalid',
                'libphonenumber_invalidcountry' => 'libphonenumber_invalidcountry',
                'libphonenumber_invalidregion' => 'libphonenumber_invalidregion',
                'libphonenumber_notanumber' => 'libphonenumber_notanumber',
                'libphonenumber_toolong' => 'libphonenumber_toolong',
                'libphonenumber_tooshort' => 'libphonenumber_tooshort',
                'libphonenumber_tooshortidd' => 'libphonenumber_tooshortidd',
                'loading' => 'Loading',
                'more' => 'more',
                'number_thousands_separator' => [
                    'number_thousands_separator', null, ','
                ],
                'sms_success' => 'sms_success'
              )
            );
            // Add libphonenumber.js strings
            $this->jsTranslations()->addStrings(
              array(
                "Phone number invalid" => 'libphonenumber_invalid',
                "Invalid country calling code" => 'libphonenumber_invalidcountry',
                "Invalid region code" => 'libphonenumber_invalidregion',
                "The string supplied did not seem to be a phone number" => 'libphonenumber_notanumber',
                "The string supplied is too long to be a phone number" => 'libphonenumber_toolong',
                "The string supplied is too short to be a phone number" => 'libphonenumber_tooshort',
                "Phone number too short after IDD" => 'libphonenumber_tooshortidd'
              )
            );
            // Deal with cart stuff:
            $cart = $this->cart();
            if ($cart->isActive()) {
              $this->headScript()->appendFile("vendor/cookies.js");
              $this->headScript()->appendFile("cart.js");
              $domain = $cart->getCookieDomain();
              if (!empty($domain)) {
                $this->headScript()->appendScript(
                  'VuFind.cart.setDomain("' . $domain . '");'
                );
              }
              $cookiePath = $cart->getCookiePath();
              if (!empty($cookiePath)) {
                $this->headScript()->appendScript(
                  'VuFind.cart.setCookiePath("' . $cookiePath . '");'
                );
              }
              $this->jsTranslations()->addStrings(
                array(
                  'addBookBag' => 'Add to Book Bag',
                  'bookbagFull' => 'bookbag_full_msg',
                  'bookbagMax' => $cart->getMaxSize(),
                  'bookbagStatusFull' => 'bookbag_full',
                  'confirmDelete' => 'confirm_delete',
                  'confirmEmpty' => 'bookbag_confirm_empty',
                  'itemsAddBag' => 'items_added_to_bookbag',
                  'itemsInBag' => 'items_already_in_bookbag',
                  'removeBookBag' => 'Remove from Book Bag',
                  'viewBookBag' => 'View Book Bag'
                )
              );
            }
            $this->headScript()->appendScript(
              'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
            );
          }

          // Session keep-alive
          if ($this->KeepAlive()) {
              $this->headScript()->appendScript('var keepAliveInterval = '
                . $this->KeepAlive());
              $this->headScript()->appendFile("keep_alive.js");
          }
        ?>
    <?
    $root = rtrim($this->url('home'), '/');
    $translations = $this->jsTranslations()->getJSON();
    $dsb = DEFAULT_SEARCH_BACKEND;
    $setupJS = <<<JS
VuFind.path = '{$root}';
VuFind.defaultSearchBackend = '{$dsb}';
VuFind.addTranslations({$translations});
JS;
    $this->headScript()->appendScript($setupJS);
    ?>
    <?=$this->headScript()?>
</head>
<body>
<? // Set up the search box -- there are three possible cases:
// 1. No search box was set; we should default to the normal box
// 2. It was set to false; we should display nothing
// 3. It is set to a custom string; we should display the provided version
// Set up default search box if no data was provided from the template;
// this covers case 1.  Cases 2 and 3 are then covered by logic below.
if (!isset($this->layout()->searchbox)) {
    $this->layout()->searchbox = $this->render('search/searchbox.phtml');
}
?>
<header role="banner" class="header hidden-print">
    <div class="container nav-bar">
        <div class="row" style="padding-bottom: 1em;">
            <div class="col-sm-12 menu-bar">

                <? $account = $this->auth()->getManager(); ?>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="hds-icon-menu"></span>
                    </button>
                    <!--
    <a role="logo" class="navbar-brand" href="<?= $this->url('home') ?>">VuFind</a>
    -->
                </div>

                <? if (!isset($this->layout()->renderingError)): ?>
                    <div class="collapse navbar-collapse" id="header-collapse">
                        <ul role="navigation" class="nav navbar-nav navbar-right">
                            <? if ($this->feedback()->tabEnabled()): ?>
                                <li>
                                    <a id="feedbackLink" class="modal-link" href="<?= $this->url('feedback-home') ?>"><i
                                                class="fa fa-envelope"></i> <?= $this->transEsc("Feedback") ?></a>
                                </li>
                            <? endif; ?>
                            <? $cart = $this->cart();
                            if ($cart->isActive()): ?>
                                <li id="cartSummary">
                                    <a id="cartItems" class="modal-link" title="<?= $this->transEsc('View Book Bag') ?>"
                                       href="<?= $this->url('cart-home') ?>"><i class="fa fa-suitcase"></i>
                                        <strong><?= count($cart->getItems()) ?></strong> <?= $this->transEsc('items') ?><?= $cart->isFull() ? ' (' . $this->transEsc('bookbag_full') . ')' : '' ?>
                                    </a>
                                </li>
                            <? endif; ?>
                            <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
                                <li class="logoutOptions<? if (!$account->isLoggedIn()): ?> hidden<? endif ?>">
                                    <a href="<?= $this->url('myresearch-home', array(), array('query' => array('redirect' => 0))) ?>"
                                       class="modal-link" title="<?= $this->transEsc("Your Account") ?>"><span
                                                class="hds-icon-home"></span> <?= $this->transEsc("Your Account") ?></a>
                                </li>
                                <li class="logoutOptions<? if (!$account->isLoggedIn()): ?> hidden<? endif ?>">
                                    <a href="<?= $this->url('myresearch-logout') ?>" class="modal-link"
                                       title="<?= $this->transEsc("Log Out") ?>"><span
                                                class="hds-icon-logout"></span> <?= $this->transEsc("Log Out") ?></a>
                                </li>
                                <li id="loginOptions"<? if ($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
                                    <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                                        <a href="<?= $this->escapeHtmlAttr($sessionInitiator) ?>"><i
                                                    class="fa fa-sign-in"></i> <?= $this->transEsc("Institutional Login") ?></a>
                                    <? else: ?>
                                        <a href="<?= $this->url('myresearch-userlogin') ?>" class="modal-link"
                                           title="<?= $this->transEsc("Login") ?>"><i
                                                    class="hds-icon-login"></i> <?= $this->transEsc("Login") ?></a>
                                    <? endif; ?>
                                </li>
                            <? endif; ?>

                            <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
                                <li class="dropdown">
                                    <form method="post" name="themeForm" action="" id="themeForm">
                                        <input type="hidden" name="ui"/>
                                    </form>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc("Theme") ?> <b
                                                class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <? foreach ($this->layout()->themeOptions as $current): ?>
                                            <li<?= $current['selected'] ? ' class="active"' : '' ?>><a href="#"
                                                                                                       onClick="document.themeForm.ui.value='<?= $this->escapeHtmlAttr($current['name']) ?>';document.themeForm.submit()"><?= $this->transEsc($current['desc']) ?></a>
                                            </li>
                                        <? endforeach; ?>
                                    </ul>
                                </li>
                            <? endif; ?>

                            <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
                                <li class="language dropdown">
                                    <form method="post" name="langForm" id="langForm">
                                        <input type="hidden" name="mylang" id="mylang"/>
                                    </form>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                                            <li <?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" class="lang-switch" data-langcode="<?=$langCode?>" ><?=$this->displayLanguageOption($langName)?></a></li>
                                        <? endforeach; ?>
                                    </ul>
                                </li>
                            <? endif; ?>
                            <li class="dropdown">
                                <a href="asd" class="dropdown-toggle"
                                   data-toggle="dropdown"><?= $this->transEsc('Static Pages') ?><b
                                            class="caret"></b></a>
                                <? //$stp = new \Hebis\Controller\StaticPagesController();

                                ?>
                                <ul class="dropdown-menu">
                                    <li><a href="">Blubb</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                <? endif; ?>

            </div>

            <div class="navbar-header hidden-xs col-sm-3 col-md-3 col-lg-2">
                <?= $this->render('logo.phtml') ?>
            </div>
            <section class="searchbox col-xs-12 col-sm-9 col-md-9 col-lg-10" style="min-height:60px;">
                <?=$this->layout()->searchbox ?>
            </section>
        </div>

    </div>

</header>

<?= $nav->getNav(); ?>
<div id="main-content" role="main" class="main template-dir-<?= $this->templateDir ?> template-name-<?= $this->templateName ?>">

    <div class="container">



            <? if ((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
                && !empty($this->layout()->breadcrumbs)
            ): ?>
                <ul class="breadcrumb hidden-print hidden-xs hidden-xs">
                    <li>
                        <a href="<?= $this->basePath() ?>"><span class="hds-icon-home"><!-- --></span></a>
                    </li>
                    <? if (is_array($this->layout()->breadcrumbs)): ?>
                        <? if (count($this->layout()->breadcrumbs) > 1): ?>
                            <?= $this->render('breadcrumbs/multi.phtml', array(
                                'parents' => $this->layout()->breadcrumbs,
                                'title' => $this->layout()->title,
                                'end' => $this->layout()->breadcrumbEnd,
                                'from' => $this->layout()->from
                            )) ?>
                        <? else: ?>
                            <?= $this->render('breadcrumbs/default.phtml', array(
                                'parents' => $this->layout()->breadcrumbs,
                                'title' => $this->layout()->title
                            )) ?>
                        <? endif; ?>
                    <? else: ?>
                        <?= $this->layout()->breadcrumbs ?>
                    <? endif; ?>
                </ul>
            <? endif; ?>

            <? /*if ($this->layout()->searchbox !== false): ?>
                <section class="search-box">
                    <?=$this->layout()->searchbox ?>
                </section>
            <? endif; */?>


            <section class="content">
                <?= $this->layout()->content ?>
            </section>
        </div>
</div>
<footer role="contentinfo" class="hidden-print">
    <div class="container">
        <?= $this->render('footer.phtml') ?>
        <?= $this->render('poweredby.phtml') ?>
        <div id="height-offset-workaround"><!-- --></div>
    </div>
</footer>
<!-- MODAL IN CASE WE NEED ONE -->
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 id="modalTitle" class="modal-title"></h4>
            </div>
            <div class="modal-body"><?= $this->transEsc('Loading') ?>...</div>
        </div>
    </div>
</div>
<?= $this->googleanalytics() ?>
<?= $this->piwik() ?>
</body>
</html>
