<?= $this->doctype('HTML5') ?>
<html lang="<?= $this->layout()->userLang ?>">
<head>
    <base href="<?= $this->basePath() ?>">
    <? $this->headThemeResources() ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>

    <?= $this->headMeta() ?>
    <?= $this->headTitle() ?>
    <style media="screen" type="text/css">
        @font-face {
            font-family: 'vufind-hds';
            src: url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.eot?45523202');
            src: url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.eot?45523202#iefix') format('embedded-opentype'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.woff2?45523202') format('woff2'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.woff?45523202') format('woff'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.ttf?45523202') format('truetype'),
            url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.svg?45523202#vufind-hds') format('svg');
            font-weight: normal;
            font-style: normal;
        }
        /* Chrome hack: SVG is rendered more smooth in Windozze. 100% magic, uncomment if you need it. */
        /* Note, that will break hinting! In other OS-es font will be not as sharp as it could be */

        @media screen and (-webkit-min-device-pixel-ratio:0) {
            @font-face {
                font-family: 'vufind-hds';
                src: url('<?= $this->basePath() ?>/themes/hebisbs3/font/vufind-hds.svg?45523202#vufind-hds') format('svg');
            }
        }
    </style>
    <?
    // Set up OpenSearch link:
    $this->headLink(
        array(
            'href' => $this->url('search-opensearch') . '?method=describe',
            'type' => 'application/opensearchdescription+xml',
            'title' => $this->transEsc('Library Catalog Search'),
            'rel' => 'search'
        )
    );
    ?>
    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <?
    // Set global path for Javascript code:
    $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

    // Deal with cart stuff:
    if (!isset($this->renderingError)) {
        $cart = $this->cart();
        $this->jsTranslations()->addStrings(
            array(
                'bulk_email_success' => 'bulk_email_success',
                'bulk_save_success' => 'bulk_save_success',
                'close' => 'close',
                'loading' => 'Loading',
                'sms_success' => 'sms_success'
            )
        );
        if ($cart->isActive()) {
            $this->headScript()->appendFile("vendor/cookies.js");
            $this->headScript()->appendFile("cart.js");
            $domain = $cart->getCookieDomain();
            $this->headScript()->appendScript(
                'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
            );
            $this->jsTranslations()->addStrings(
                array(
                    'bulk_noitems_advice' => 'bulk_noitems_advice',
                    'confirmDelete' => 'confirm_delete',
                    'confirmEmpty' => 'bookbag_confirm_empty',
                    'viewBookBag' => 'View Book Bag',
                    'addBookBag' => 'Add to Book Bag',
                    'removeBookBag' => 'Remove from Book Bag',
                    'itemsAddBag' => 'items_added_to_bookbag',
                    'itemsInBag' => 'items_already_in_bookbag',
                    'bookbagMax' => $cart->getMaxSize(),
                    'bookbagFull' => 'bookbag_full_msg',
                    'bookbagStatusFull' => 'bookbag_full',
                    'no_tags' => 'No Tags'
                )
            );
        }
        $this->headScript()->appendScript($this->jsTranslations()->getScript());
    }

    // Session keep-alive
    if ($this->KeepAlive()) {
        $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
        $this->headScript()->appendFile("keep_alive.js");
    }
    ?>
    <?= $this->headScript() ?>
</head>
<body>
<? // Set up the search box -- there are three possible cases:
// 1. No search box was set; we should default to the normal box
// 2. It was set to false; we should display nothing
// 3. It is set to a custom string; we should display the provided version
// Set up default search box if no data was provided from the template;
// this covers case 1.  Cases 2 and 3 are then covered by logic below.
if (!isset($this->layout()->searchbox)) {
    $this->layout()->searchbox = $this->render('search/searchbox.phtml');
}
?>
<header role="banner" class="header hidden-print">
    <div class="container nav-bar">
        <div class="row">
            <div class="col-sm-12 menu-bar">

                <div class="collapse navbar-collapse" id="header-collapse">

                    <ul role="navigation" class="nav navbar-nav navbar-right">

                        <li class="logoutOptions hidden">
                            <a href="/MyResearch/Home?redirect=0" class="modal-link" title="My swissbib"><i class="fa fa-user"></i>My swissbib:               </a>
                        </li>
                        <li class="logoutOptions hidden">
                            <a href="/MyResearch/Logout" class="modal-link" title="Abmelden"><i class="fa fa-sign-out"></i>Abmelden</a>
                        </li>
                        <li id="loginOptions">
                            <a href="https://www.swissbib.ch/MyResearch/UserLogin?target=https%3A%2F%2Fwww.swissbib.ch%2FMyResearch%2FHome%3Fauth_method%3DShibboleth"><i class="fa fa-sign-in"></i>Anmeldung über Ihre Einrichtung</a>
                        </li>


                        <li class="dropdown">
                            <form method="post" name="langForm" action="" id="langForm">
                                <input type="hidden" name="mylang">
                            </form>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sprache <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li class="active">
                                    <a href="#" onclick="document.langForm.mylang.value='de';document.langForm.submit()">
                                        <span class="visible-xs">Deutsch</span>
                                        <span class="hidden-xs">DE</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onclick="document.langForm.mylang.value='fr';document.langForm.submit()">
                                        <span class="visible-xs">Français</span>
                                        <span class="hidden-xs">FR</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onclick="document.langForm.mylang.value='it';document.langForm.submit()">
                                        <span class="visible-xs">Italiano</span>
                                        <span class="hidden-xs">IT</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onclick="document.langForm.mylang.value='en';document.langForm.submit()">
                                        <span class="visible-xs">English</span>
                                        <span class="hidden-xs">EN</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="navbar-header col-sm-4 col-xs-10 col-md-2">
                <?= $this->render('logo.phtml') ?>
            </div>
            <section class="searchbox col-sm-8 col-xs-12 col-md-10">
                <?=$this->layout()->searchbox ?>
            </section>
        </div>

    </div>
    <!--
    <div class="container navbar">
        <a class="sr-only" href="#content"><?= $this->transEsc('Skip to content') ?></a>
        <? // echo $this->render('header.phtml') ?>
    </div>
    -->
</header>
<div id="main-content" role="main" class="main template-dir-<?= $this->templateDir ?> template-name-<?= $this->templateName ?>">

    <div class="container">

        <div class="container-inner">

            <? if ((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
                && !empty($this->layout()->breadcrumbs)
            ): ?>
                <ul class="breadcrumb hidden-print hidden-xs hidden-xs">
                    <li>
                        <a href="<?= $this->basePath() ?>"><span class="hds-icon-home"><!-- --></span></a>
                    </li>
                    <? if (is_array($this->layout()->breadcrumbs)): ?>
                        <? if (count($this->layout()->breadcrumbs) > 1): ?>
                            <?= $this->render('breadcrumbs/multi.phtml', array(
                                'parents' => $this->layout()->breadcrumbs,
                                'title' => $this->layout()->title,
                                'end' => $this->layout()->breadcrumbEnd,
                                'from' => $this->layout()->from
                            )) ?>
                        <? else: ?>
                            <?= $this->render('breadcrumbs/default.phtml', array(
                                'parents' => $this->layout()->breadcrumbs,
                                'title' => $this->layout()->title
                            )) ?>
                        <? endif; ?>
                    <? else: ?>
                        <?= $this->layout()->breadcrumbs ?>
                    <? endif; ?>
                </ul>
            <? endif; ?>

            <? /*if ($this->layout()->searchbox !== false): ?>
                <section class="search-box">
                    <?=$this->layout()->searchbox ?>
                </section>
            <? endif; */?>


            <section class="content">
                <?= $this->layout()->content ?>
            </section>
        </div>
    </div>
</div>
<footer role="contentinfo" class="hidden-print">
    <div class="container">
        <?= $this->render('footer.phtml') ?>
        <?= $this->layout()->poweredBy ?>
    </div>
</footer>
<!-- MODAL IN CASE WE NEED ONE -->
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 id="modalTitle" class="modal-title"></h4>
            </div>
            <div class="modal-body"><?= $this->transEsc('Loading') ?>...</div>
        </div>
    </div>
</div>
<?= $this->googleanalytics() ?>
<?= $this->piwik() ?>
</body>
</html>
